### ISSUE TITLE
Unable to compile `mhlo.round_nearest_afz` in Vulkan backend

### ISSUE THREAD

**Issue by edubart** [google/iree#8680] opened 2022-03-29 22:56 UTC
The following MLIR code:

```llvm
func @main() -> tensor<16x4096xf32> attributes { llvm.emit_c_interface } {
  %min = mhlo.constant dense<0.0> : tensor<f32>
  %max = mhlo.constant dense<1.0> : tensor<f32>
  %shape = mhlo.constant dense<[16, 4096]> : tensor<2xi64>
  %2 = "mhlo.rng_uniform"(%min, %max, %shape) : (tensor<f32>, tensor<f32>, tensor<2xi64>) -> tensor<16x4096xf32>
  %3 = "mhlo.round_nearest_afz"(%2) : (tensor<16x4096xf32>) -> tensor<16x4096xf32>
  return %3 : tensor<16x4096xf32>
}
```

Fails to compile to in the `vulkan` backend:
```llvm
$ iree-translate test.mlir \
	-iree-input-type=mhlo \
	-iree-mlir-to-vm-bytecode-module \
	-iree-hal-target-backends=vulkan

mlir/matmul.mlir:6:8: error: failed to legalize operation 'math.copysign'
  %3 = "mhlo.round_nearest_afz"(%2) : (tensor<16x4096xf32>) -> tensor<16x4096xf32>
       ^
mlir/matmul.mlir:1:1: note: called from
func @main() -> tensor<16x4096xf32> attributes { llvm.emit_c_interface } {
^
mlir/matmul.mlir:6:8: note: see current operation: %66 = "math.copysign"(%65, %59) : (f32, f32) -> f32
  %3 = "mhlo.round_nearest_afz"(%2) : (tensor<16x4096xf32>) -> tensor<16x4096xf32>
       ^
mlir/matmul.mlir:6:8: error: failed to run translation of source executable to target executable for backend #hal.executable.target<"vulkan", "vulkan-spirv-fb", {spv.target_env = #spv.target_env<#spv.vce<v1.3, [Shader, GroupNonUniform, GroupNonUniformVote, GroupNonUniformArithmetic, GroupNonUniformBallot, GroupNonUniformShuffle, GroupNonUniformShuffleRelative], [SPV_KHR_storage_buffer_storage_class]>, SwiftShader:CPU, {cooperative_matrix_properties_nv = [], max_compute_shared_memory_size = 16384 : i32, max_compute_workgroup_invocations = 128 : i32, max_compute_workgroup_size = dense<[128, 128, 64]> : vector<3xi32>, subgroup_size = 4 : i32}>}>
  %3 = "mhlo.round_nearest_afz"(%2) : (tensor<16x4096xf32>) -> tensor<16x4096xf32>
       ^
mlir/matmul.mlir:1:1: note: called from
func @main() -> tensor<16x4096xf32> attributes { llvm.emit_c_interface } {
```

Switching the backend to `cuda` or `dylib` it compiles with success. Returning `%2` instead of `%3` also compiles in the Vulkan backend, so the `mhlo.round_nearest_afz` line triggers the issue.

Environment: I am using latest commit in main branch.

**Comment by ScottTodd** [comment] 2022-03-29 23:15
Nearly a duplicate of https://github.com/google/iree/issues/7618 (VMVX is also missing a `math.copysign` lowering)

**Comment by ScottTodd** [comment] 2022-03-29 23:20
and we have some tests that we could enable once this is working: 

https://github.com/google/iree/blob/db649e0f53c6e8acb21cf00cc8b9861d9bec1512/iree/test/e2e/xla_ops/round.mlir#L1-L6
https://github.com/google/iree/blob/db649e0f53c6e8acb21cf00cc8b9861d9bec1512/iree/test/e2e/xla_ops/BUILD#L311
https://github.com/google/iree/blob/db649e0f53c6e8acb21cf00cc8b9861d9bec1512/iree/test/e2e/xla_ops/BUILD#L382

**Comment by benvanik** [comment] 2022-03-29 23:23
copysign is pretty simple, just some bit twiddling, we should be able to expand this lowering: https://git.musl-libc.org/cgit/musl/tree/src/math/copysignf.c

**Comment by antiagainst** [comment] 2022-04-01 19:28
Landed https://reviews.llvm.org/D122910 in the upstream. #8728 can land after next integration to close this issue.

**Closed** 2022-04-05 16:58 UTC
Labels: bug 🐞, help wanted, codegen/spirv
