### ISSUE TITLE
Error messages need to be plumbed through the C-API properly

### ISSUE THREAD

**Issue by stellaraccident** [google/iree#133] opened 2019-11-12 00:50 UTC
Currently, just a status code is returned, which is not helpful. There is one DLOG(ERROR) in base/api_util.h which is the only way to get a more detailed error.

**Comment by benvanik** [comment] 2019-11-12 01:38
What kind of info would you like? Full stack trace? Or is a message enough? Do you want to know it at the exact call site or is a push/callback interface ok for reporting?

Thinking we could add an optional output arg to functions that would return detailed error information and then add it where we expect it to be useful (loading, invocation, etc). Or, similar to Vulkan, could have an optional error reporter get registered and receive errors with much more information/materialized on demand. We probably want to have a logging sink anyway to allow routing up through applications (as many embedding applications have their own logging systems).

**Comment by benvanik** [comment] 2020-03-19 17:36
Duplicate of #265.

**Closed by benvanik** 2020-03-19 17:36 UTC
