### ISSUE TITLE
Can not execute mhlo.dynamic-slice end-to-end in IREE

### ISSUE THREAD

**Issue by hanhanW** [google/iree#5620] opened 2021-04-26 18:29 UTC
Some tensor.extract op would be outside dispatches, e.g.,

```mlir
// *** IR Dump Before mlir::iree_compiler::IREE::Flow::(anonymous namespace)::DispatchLinalgOnTensorsPass ***
func @dynamic_slice(%arg0: tensor<2x512xi32>, %arg1: tensor<i32>, %arg2: tensor<i32>) -> tensor<512xi32> {
  %c1_i32 = constant 1 : i32
  %c0_i32 = constant 0 : i32
  %c1 = constant 1 : index
  %c512 = constant 512 : index
  %c2 = constant 2 : index
  %0 = tensor.extract %arg1[] : tensor<i32>
  %1 = cmpi slt, %0, %c1_i32 : i32
  %2 = select %1, %0, %c1_i32 : i32
  %3 = cmpi sgt, %2, %c0_i32 : i32
  %4 = select %3, %2, %c0_i32 : i32
  %5 = index_cast %4 : i32 to index
  %6 = tensor.extract %arg2[] : tensor<i32>
  %7 = cmpi slt, %6, %c0_i32 : i32
  %8 = select %7, %6, %c0_i32 : i32
  %9 = cmpi sgt, %8, %c0_i32 : i32
  %10 = select %9, %8, %c0_i32 : i32
  %11 = index_cast %10 : i32 to index
  %12 = flow.tensor.slice %arg0[%5, %11 for %c1, %c512] : tensor<2x512xi32>{%c2, %c512} -> tensor<1x512xi32>{%c1, %c512}
  %13 = flow.tensor.reshape %12 : tensor<1x512xi32> -> tensor<512xi32>
  return %13 : tensor<512xi32>
}
```

I could be wrong. I think we don't handle tensor.extract at flow level, so it will live forever, and will get failure in ConvertToHalPass because all tensor type will be rewritten to buffer type. In this case, I think we should rewrite tensor.extract to flow load var stuff in ConvertToHalPass? 

To rerpo:

```mlir
func @dynamic_slice(%arg: tensor<2x512xi32>, %start1: tensor<i64>, %start2: tensor<i64>) -> tensor<512xi32> {
  %0 = "mhlo.dynamic-slice"(%arg, %start1, %start2) {
    slice_sizes = dense<[1, 512]> : tensor<2xi64>
  } : (tensor<2x512xi32>, tensor<i64>, tensor<i64>) -> tensor<512xi32>
  return %0 : tensor<512xi32>
}
```

Run:

$ iree-translate --iree-mlir-to-vm-bytecode-module --iree-hal-target-backends=vulkan-spirv dynamic_slice.mlir

**Comment by benvanik** [comment] 2021-04-26 18:51
We have a tensor.extract -> flow lowering here:
https://github.com/google/iree/blob/96e9c4946399f2a0df6794252c77506e9ac1c9a5/iree/compiler/Dialect/Flow/Conversion/StandardToFlow/ConvertStandardToFlow.cpp

And that later gets lowered to IREE::HAL::BufferLoadOp here:
https://github.com/google/iree/blob/b7381623652bdcfd67ad2cf836f503c9d634c567/iree/compiler/Dialect/HAL/Conversion/FlowToHAL/ConvertTensorOps.cpp

If we are generating these tensor_extract ops during flow->hal lowering, we could either have the tensor->flow patterns added to allow for transitive lowering or add dedicated tensor.extract->hal ops in `iree/compiler/Dialect/HAL/Conversion/StandardToHAL/`.

**Comment by benvanik** [comment] 2021-04-26 18:52
(probably cleaner to do the standard->hal lowering)

**Comment by hanhanW** [comment] 2021-04-26 18:56
Now the reason is the order of passes.

tensor.extract -> flow lowering is used in `PrePartitioningConversionPass`. But the tensor.extract ops are created after it. Because it's coming from mhlo.dynamic-slice.

https://github.com/google/iree/blob/691d0018b3660859a416943b5cfc41272d1e1ab6/iree/compiler/Dialect/Flow/Transforms/Passes.cpp#L195-L204

**Comment by hanhanW** [comment] 2021-04-26 19:01
I think we should move the pass a bit earlier because some non-Linalg ops would be created when lowering mhlo ops to Linalg on tensors e.g., subtensor, subtensor_insert, tenser.extract, etc.

cc @MaheshRavishankar

**Comment by benvanik** [comment] 2021-04-26 19:01
The entirety of pre-partioning conversion should be going away in the linalg on tensors world - all HLO should be turned into linalg ops before coming into IREE.

**Comment by hanhanW** [comment] 2021-04-27 15:07
Adding `passManager.addNestedPass<FuncOp>( IREE::Flow::createPrePartitioningConversionPass()); ` right after it does address the issue -- can compile mhlo.dynamic-slice end-to-end.

**Comment by benvanik** [comment] 2021-04-27 15:19
You should try moving all the HLO passes to https://github.com/google/iree/blob/a935ddfc204535c8b95c7c485a1ec8e1e2aab41c/iree/compiler/Dialect/Flow/Transforms/Passes.cpp#L68 - I think that currently won't work because of VMLA but should work for the codegen path - after that point we can run a verification that there are no more hlo ops in the IR. The goal is then to move that buildHLOInputTransformPassPipeline out to integrations/tensorflow/, but at least getting HLO stuff into it in the current location will help us solve issues like this.

**Comment by hanhanW** [comment] 2021-04-27 15:58
Sounds good! note -- it also works when moving it to the function.

**Comment by hanhanW** [comment] 2021-05-11 23:30
Moving it to buildHLOInputTransformPassPipeline will introduce new issues. I did not look into details. One of the issues is FlowLegalizeInputTypes should be fixed because there will be i64 stuff in Linalg ops.


If adding `createPrePartitioningConversionPass` right after  MHLO to Linalg conversion, it will introduce other issues in reduce op compilation:

```mlir
func @reduce_sum_1x10xf32() attributes { iree.module.export } {
  %0 = iree.unfoldable_constant dense<[[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]]> : tensor<1x10xf32>
  %1 = iree.unfoldable_constant dense<0.0> : tensor<f32>
  %res = "mhlo.reduce"(%0, %1) ( {
  ^bb0(%arg0: tensor<f32>, %arg1: tensor<f32>):   // no predecessors
    %3 = "mhlo.add"(%arg0, %arg1) : (tensor<f32>, tensor<f32>) -> tensor<f32>
    "mhlo.return"(%3) : (tensor<f32>) -> ()
  }) {dimensions = dense<1> : tensor<1xi64>} : (tensor<1x10xf32>, tensor<f32>) -> tensor<1xf32>
  check.expect_almost_eq_const(%res, dense<55.0> : tensor<1xf32>) : tensor<1xf32>
  return
}
```

We will hit `unsupported interface function argument 0 type 'f32'; requires tensors or simple primitive values (i32, etc)` in `MaterializeInterfaces2Pass`. I suspect the reason is that `%2 = flow.tensor.load %1 : tensor<f32>` is created.

Without adding the pass to handle `tensor.extract`, it will be replaced with `memref.load` in bufferization pass.

This does not work for dynamic-slice case because no linalg ops are generated. It won't be pulled into any `flow.dispatch.workgroups`, so we don't have patterns to handle it.

I think maybe a proper way to handle it is to run the pattern again right after `createOutlineDispatchRegions2Pass` pass. If there are other extract ops outside dispatches, they will be replaced with `flow.tensor.load`.

https://github.com/google/iree/blob/a93ff6134aab4c47d1d4d46eb7eb6e48cf8a5665/iree/compiler/Dialect/Flow/Transforms/Passes.cpp#L231-L240

It will work for both dynamic-slice and reduce cases. Testing if there are other issues if we put it here...

**Comment by benvanik** [comment] 2021-05-12 19:18
I'm not sure I follow. Are you saying that something is doing a tensor.extract _outside of a dispatch region_ and then _passing the extracted value into a dispatch region_? If so, we shouldn't do that and should be folding the tensor.extract into the dispatch region - otherwise we're performing a host readback of device memory to then pass it right back to the device.

**Comment by MaheshRavishankar** [comment] 2021-05-12 19:32
> I'm not sure I follow. Are you saying that something is doing a tensor.extract _outside of a dispatch region_ and then _passing the extracted value into a dispatch region_? If so, we shouldn't do that and should be folding the tensor.extract into the dispatch region - otherwise we're performing a host readback of device memory to then pass it right back to the device.

If that is the thing it is easy to fix

**Comment by hanhanW** [comment] 2021-05-12 19:33
Yes, that is what I'm saying. I think this happens only if there are no linalg ops. E.g., if there is a single dynamic-slice op, it will be lowered to

```
func @dynamic_slice(%arg0: tensor<2x512xi32>, %arg1: tensor<i32>, %arg2: tensor<i32>) -> tensor<512xi32> {
  %c1_i32 = constant 1 : i32
  %c0_i32 = constant 0 : i32
  %c1 = constant 1 : index
  %c512 = constant 512 : index
  %c2 = constant 2 : index
  %0 = tensor.extract %arg1[] : tensor<i32>
  %1 = cmpi slt, %0, %c1_i32 : i32
  %2 = select %1, %0, %c1_i32 : i32
  %3 = cmpi sgt, %2, %c0_i32 : i32
  %4 = select %3, %2, %c0_i32 : i32
  %5 = index_cast %4 : i32 to index
  %6 = tensor.extract %arg2[] : tensor<i32>
  %7 = cmpi slt, %6, %c0_i32 : i32
  %8 = select %7, %6, %c0_i32 : i32
  %9 = cmpi sgt, %8, %c0_i32 : i32
  %10 = select %9, %8, %c0_i32 : i32
  %11 = index_cast %10 : i32 to index
  %12 = flow.tensor.slice %arg0[%5, %11 for %c1, %c512] : tensor<2x512xi32>{%c2, %c512} -> tensor<1x512xi32>{%c1, %c512}
  %13 = flow.tensor.reshape %12 : tensor<1x512xi32> -> tensor<512xi32>
  return %13 : tensor<512xi32>
}
```

In this case, no dispatches will be created?

**Comment by MaheshRavishankar** [comment] 2021-05-12 22:48
Ok, so I should have just run the test with ToT of tree and `iree-translate`. If I had done that I would have found that the current IR before and after dispatch region creation would be

```
/ *** IR Dump After CSE ***
func @dynamic_slice(%arg0: tensor<2x512xi32>, %arg1: tensor<i32>, %arg2: tensor<i32>) -> tensor<512xi32> {
  %c1_i32 = constant 1 : i32
  %c0_i32 = constant 0 : i32
  %0 = tensor.extract %arg1[] : tensor<i32>
  %1 = cmpi slt, %0, %c1_i32 : i32
  %2 = select %1, %0, %c1_i32 : i32
  %3 = cmpi sgt, %2, %c0_i32 : i32
  %4 = select %3, %2, %c0_i32 : i32
  %5 = index_cast %4 : i32 to index
  %6 = tensor.extract %arg2[] : tensor<i32>
  %7 = cmpi slt, %6, %c0_i32 : i32
  %8 = select %7, %6, %c0_i32 : i32
  %9 = cmpi sgt, %8, %c0_i32 : i32
  %10 = select %9, %8, %c0_i32 : i32
  %11 = index_cast %10 : i32 to index
  %12 = subtensor %arg0[%5, %11] [1, 512] [1, 1] : tensor<2x512xi32> to tensor<512xi32>
  return %12 : tensor<512xi32>
}

// *** IR Dump After DispatchLinalgOnTensors ***
func @dynamic_slice(%arg0: tensor<2x512xi32>, %arg1: tensor<i32>, %arg2: tensor<i32>) -> tensor<512xi32> {
  %c1_i32 = constant 1 : i32
  %c0_i32 = constant 0 : i32
  %c512 = constant 512 : index
  %c1 = constant 1 : index
  %0 = tensor.extract %arg1[] : tensor<i32>
  %1 = cmpi slt, %0, %c1_i32 : i32
  %2 = select %1, %0, %c1_i32 : i32
  %3 = cmpi sgt, %2, %c0_i32 : i32
  %4 = select %3, %2, %c0_i32 : i32
  %5 = index_cast %4 : i32 to index
  %6 = tensor.extract %arg2[] : tensor<i32>
  %7 = cmpi slt, %6, %c0_i32 : i32
  %8 = select %7, %6, %c0_i32 : i32
  %9 = cmpi sgt, %8, %c0_i32 : i32
  %10 = select %9, %8, %c0_i32 : i32
  %11 = index_cast %10 : i32 to index
  %12 = flow.dispatch.workgroups[%c512, %c1, %c1](%arg0, %5, %11) : (tensor<2x512xi32>, index, index) -> tensor<512xi32> =
      (%arg3: !flow.dispatch.tensor<readonly:2x512xi32>, %arg4: index, %arg5: index, %arg6: !flow.dispatch.tensor<writeonly:512xi32>) {
    %13 = flow.dispatch.tensor.load %arg3, offsets = [], sizes = [], strides = [] : !flow.dispatch.tensor<readonly:2x512xi32> -> tensor<2x512xi32>
    %14 = subtensor %13[%arg4, %arg5] [1, 512] [1, 1] : tensor<2x512xi32> to tensor<512xi32>
    flow.dispatch.tensor.store %14, %arg6, offsets = [], sizes = [], strides = [] : tensor<512xi32> -> !flow.dispatch.tensor<writeonly:512xi32>
    flow.return
  }
  return %12 : tensor<512xi32>
}

```

Now I understand what was happening. There was a bug in the `subtensor` -> `flow.slice` lowering which is now fixed. So the `subtensor` moves into the dispatch region as expected.
THe issue is now all the scalar operations that are left outside. These should be in the dispatch region as well which is a simple fix. Have this working locally. Sending out PR.

**Comment by benvanik** [comment] 2021-05-12 22:53
Awesome!

As a note I am (as part of general VMVX work) flipping on support for f32/i64 in the VM, so it should be able to handle most of these kind of situations in the future - but as mentioned it's no good to read back tensor values so folding chains of simple ops that originate from a tensor and feed into dispatch regions is a good idea (same with when the ops extracting tensors that flow out of dispatch regions into the dispatch region). With the detensoring work I suspect we'll end up with situations like that - where entire trees of ops are extract -> scalars -> insert and we should try to pack them into appropriate dispatches (otherwise we end up with data-dependent loop iterators synchronizing with the cpu). Having the generalized support will hopefully at least prevent these things from being blockers like this, though!

Thanks for filing the repro @hanhanW!

**Closed** 2021-05-13 00:25 UTC
Labels: codegen, compiler
