### ISSUE TITLE
Using GCC on Linux fails with error  undefined reference to `dlsym'

### ISSUE THREAD

**Issue by MaheshRavishankar** [google/iree#4915] opened 2021-02-22 21:21 UTC
Using GCC-10 on Linux fails with an undefined reference to `dlsym`. The Cmake configuration

`cmake -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DCMAKE_BUILD_TYPE=Debug`

Based on whats described here 
https://github.com/Intel-Media-SDK/MediaSDK/issues/34

The fix was to add `-Wl,--no-as-needed -ldl`

This change to CMakeLists.txt at the root directory seemed to get past it

```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 243e3e618..fc9554248 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -233,11 +233,13 @@ set(CMAKE_POSITION_INDEPENDENT_CODE TRUE)
 iree_append_list_to_string(CMAKE_C_FLAGS_DEBUG ${IREE_C_FLAGS_DEBUG_LIST})
 iree_append_list_to_string(CMAKE_CXX_FLAGS_DEBUG ${IREE_CXX_FLAGS_DEBUG_LIST})
 
+set(CMAKE_EXE_LINKER_FLAGS "-Wl,--no-as-needed -ldl")
 set(CMAKE_CXX_FLAGS_FASTBUILD "-gmlt" CACHE STRING "Flags used by the C++ compiler during fast builds." FORCE)
 set(CMAKE_C_FLAGS_FASTBUILD "-gmlt" CACHE STRING "Flags used by the C compiler during fast builds." FORCE)
 set(CMAKE_EXE_LINKER_FLAGS_FASTBUILD "-Wl,-S" CACHE STRING "Flags used for linking binaries during fast builds." FORCE)
 set(CMAKE_SHARED_LINKER_FLAGS_FASTBUILD "-Wl,-S" CACHE STRING "Flags used by the shared libraries linker binaries during fast builds." FORCE)
 mark_as_advanced(
+  CMAKE_EXE_LINKER_FLAGS
   CMAKE_CXX_FLAGS_FASTBUILD
   CMAKE_C_FLAGS_FASTBUILD
   CMAKE_EXE_LINKER_FLAGS_FASTBUILD
```

**Comment by stellaraccident** [comment] 2021-02-24 03:39
I suspect this is distribution related: is there any more details you can share on that?

(i.e. this issue does not happen with the release bot that builds on GCC 9.0.3+RHEL7 equiv, and I know it also doesn't happen on GCC 10 on that distro)

**Comment by MaheshRavishankar** [comment] 2021-02-24 18:08
I actually see this happening with GCC-10.2.1 and Debian 5.7 equiv.

**Comment by nick-furry** [comment] 2021-03-13 01:57
I got the same error while building on Ubuntu 20.04 (GCC 9.3) and the above modifications to CMakeLists.txt solved it.

**Comment by KyleHerndon** [comment] 2021-06-23 23:22
I also experienced this with GCC-10.3.0 and Ubuntu 20.04.2 LTS and benefited from the above fix

**Comment by GMNGeoffrey** [comment] 2022-06-02 22:55
I think this is a dupe of #5702 perhaps?

**Comment by GMNGeoffrey** [comment] 2022-06-14 01:31
Closing as duplicate of #5702

**Closed by GMNGeoffrey** 2022-06-14 01:31 UTC
Labels: infrastructure, infrastructure/cmake

**Comment by GMNGeoffrey** [comment] 2022-06-14 01:32
Duplicate of #5702
