### ISSUE TITLE
Bad performance in some linalg generic generated for MobileBert

### ISSUE THREAD

**Issue by ThomasRaoux** [google/iree#5647] opened 2021-04-27 21:42 UTC
After moving to linalg on tensor we generate the op below in mobile bert. We should collapse the unit dimension to avoid creating a 4D op.
```
%1479 = linalg.tensor_reshape %1474 [affine_map<(d0, d1, d2, d3) -> (d0)>, affine_map<(d0, d1, d2, d3) -> (d1)>, affine_map<(d0, d1, d2, d3) -> (d2, d3)>] : tensor<4x384x384xf16> into tensor<4x384x1x384xf16>
  %1480 = linalg.generic {indexing_maps = [affine_map<(d0, d1, d2, d3) -> (d0, d1, d2, d3)>, affine_map<(d0, d1, d2, d3) -> (d2, d3)>, affine_map<(d0, d1, d2, d3) -> (d0, d1)>, affine_map<(d0, d1, d2, d3) -> (d0, d1)>, affine_map<(d0, d1, d2, d3) -> (d0, d1, d2, d3)>], iterator_types = ["parallel", "parallel", "parallel", "parallel"]} ins(%1479, %arg1, %1476, %1478 : tensor<4x384x1x384xf16>, tensor<1x384xi32>, tensor<4x384xf16>, tensor<4x384xf16>) outs(%52 : tensor<4x384x1x384xf16>) {
  ^bb0(%arg3: f16, %arg4: i32, %arg5: f16, %arg6: f16, %arg7: f16):  // no predecessors
    %1529 = sitofp %arg4 : i32 to f16
    %1530 = mulf %1529, %cst_1091 : f16
    %1531 = mulf %1530, %cst_1092 : f16
    %1532 = addf %1531, %cst_1093 : f16
    %1533 = mulf %arg3, %cst_1090 : f16
    %1534 = addf %1533, %1532 : f16
    %1535 = subf %1534, %arg5 : f16
    %1536 = math.exp %1535 : f16
    %1537 = divf %1536, %arg6 : f16
    linalg.yield %1537 : f16
  } -> tensor<4x384x1x384xf16>
```

**Comment by MaheshRavishankar** [comment] 2021-04-27 22:10
This pass https://github.com/llvm/llvm-project/blob/main/mlir/lib/Dialect/Linalg/Transforms/DropUnitDims.cpp should be able to drop one of the unit-dimensions and fold away the reshape too.

This is the pass option https://github.com/llvm/llvm-project/blob/b19136e35256c5b21aff93ea5b55b4c142408c40/mlir/include/mlir/Dialect/Linalg/Passes.td#L25 . Should be able to use it with `iree-opt`.

Might be some over constrained checks, cause `d2` must be able to drop that dimension.

**Comment by ThomasRaoux** [comment] 2021-05-04 15:31
On latest code I do see that unit dimensions are being removed however this doesn't remove the parallel loops so we get something like this:
```
linalg.generic {indexing_maps = [affine_map<(d0, d1, d2, d3) -> (d0, d1, d3)>, affine_map<(d0, d1, d2, d3) -> (d2, d3)>, affine_map<(d0, d1, d2, d3) -> (d0, d1, d3)>], iterator_types = ["parallel", "parallel", "parallel", "parallel"]} ins(%52, %arg1 : tensor<4x384x384xf16>, tensor<1x384xi32>) outs(%53 : tensor<4x384x384xf16>)
```
Ideally we could reduce it to 3 parallel loops instead of 4. 

@MaheshRavishankar, DropUnitDimensions is not expected to handle that? Are you aware of such transformation or is it something new we need to write?

**Comment by MaheshRavishankar** [comment] 2021-05-04 15:45
It should be removed. The issue is this affine map : `affine_map<(d0, d1, d2, d3) -> (d2, d3)>` . This is used to accesses `arg1`. In theorry it should be adding a reshape to drop the dimensions `d2` in the `affine_map`. With that there would be no uses of `d2` in the affine maps and the loop would be removed.

**Comment by ThomasRaoux** [comment] 2021-05-04 19:57
You're right, DropUnitDimensions actually does the right thing. The problem is that the extra parallel dimensions are re-introduced by `populateFoldReshapeOpsByExpansionPatterns` Setting `allowFoldingUnitDimReshapes` actually fixes the performance issue in this case.

**Comment by MaheshRavishankar** [comment] 2021-05-10 22:36
I think this is fixed. Closing.

**Closed by MaheshRavishankar** 2021-05-10 22:36 UTC
Labels: performance ⚡
