### ISSUE TITLE
A link in document hub is set incorrectly

### ISSUE THREAD

**Issue by onlyoh** [google/iree#3014] opened 2020-08-27 03:55 UTC
There is a `getting started guides` link in [https://google.github.io/iree/get-started/getting-started-python](https://google.github.io/iree/get-started/getting-started-python), and it doesn't redirect to correct url, i.e., got a 404 not found page. I think it may be due to an extra `/` after the `getting started guides` link.

**Comment by ScottTodd** [comment] 2020-08-27 04:19
Duplicate of https://github.com/google/iree/issues/2029

Yeah :/ I'll see if tweaking the link syntax helps. Otherwise we could just remove that link.

**Closed** 2020-08-27 04:56 UTC
