### ISSUE TITLE
Add a pass to verify GlobalOp and initializer order within modules.

### ISSUE THREAD

**Issue by stellaraccident** [google/iree#7859] opened 2021-12-13 02:30 UTC
Segmentation fault in `ConvertUtilToStream.cpp` pattern `GlobalStoreOpExpansion` on:

```
    auto transferOp = rewriter.create<IREE::Stream::AsyncTransferOp>(
        storeOp.getLoc(), expandedGlobal.resourceOp.type(), value.resource,
        value.resourceSize, value.resourceSize, /*source_affinity=*/nullptr,
        /*result_affinity=*/nullptr);
```

This assert catches it:

```
assert(expandedGlobal.resourceOp && "Missing resource op");
```

Example program which causes crash:

```
  module  {
    util.initializer {
      %cst = arith.constant dense<1.270000e+02> : tensor<f32>
      %_params$0 = util.global.load @_params$0 : tensor<6x3xf32>
      %0 = linalg.init_tensor [6, 3] : tensor<6x3xf32>
      %1 = linalg.generic {indexing_maps = [#map1, #map1], iterator_types = ["parallel", "parallel"]} ins(%_params$0 : tensor<6x3xf32>) outs(%0 : tensor<6x3xf32>) {
      ^bb0(%arg0: f32, %arg1: f32):  // no predecessors
        %7 = math.abs %arg0 : f32
        linalg.yield %7 : f32
      } -> tensor<6x3xf32>
      %cst_0 = arith.constant 0xFF800000 : f32
      %2 = linalg.init_tensor [] : tensor<f32>
      %3 = linalg.fill(%cst_0, %2) : f32, tensor<f32> -> tensor<f32> 
      %4 = linalg.generic {indexing_maps = [#map1, #map0], iterator_types = ["reduction", "reduction"]} ins(%1 : tensor<6x3xf32>) outs(%3 : tensor<f32>) {
      ^bb0(%arg0: f32, %arg1: f32):  // no predecessors
        %7 = arith.maxf %arg0, %arg1 : f32
        linalg.yield %7 : f32
      } -> tensor<f32>
      %5 = linalg.init_tensor [] : tensor<f32>
      %6 = linalg.generic {indexing_maps = [#map2, #map2, #map2], iterator_types = []} ins(%cst, %4 : tensor<f32>, tensor<f32>) outs(%5 : tensor<f32>) {
      ^bb0(%arg0: f32, %arg1: f32, %arg2: f32):  // no predecessors
        %7 = arith.divf %arg0, %arg1 : f32
        linalg.yield %7 : f32
      } -> tensor<f32>
      util.global.store %6, @hoisted : tensor<f32>
      util.initializer.return
    }
    util.initializer {
      %_params$0 = util.global.load @_params$0 : tensor<6x3xf32>
      %hoisted = util.global.load @hoisted : tensor<f32>
      %0 = linalg.init_tensor [6, 3] : tensor<6x3xf32>
      %1 = linalg.generic {indexing_maps = [#map0, #map1], iterator_types = ["parallel", "parallel"]} ins(%hoisted : tensor<f32>) outs(%0 : tensor<6x3xf32>) {
      ^bb0(%arg0: f32, %arg1: f32):  // no predecessors
        linalg.yield %arg0 : f32
      } -> tensor<6x3xf32>
      %2 = linalg.init_tensor [6, 3] : tensor<6x3xf32>
      %3 = linalg.generic {indexing_maps = [#map1, #map1, #map1], iterator_types = ["parallel", "parallel"]} ins(%_params$0, %1 : tensor<6x3xf32>, tensor<6x3xf32>) outs(%2 : tensor<6x3xf32>) {
      ^bb0(%arg0: f32, %arg1: f32, %arg2: f32):  // no predecessors
        %10 = arith.mulf %arg0, %arg1 : f32
        linalg.yield %10 : f32
      } -> tensor<6x3xf32>
      %cst = arith.constant dense<5.000000e-01> : tensor<6x3xf32>
      %4 = linalg.init_tensor [6, 3] : tensor<6x3xf32>
      %5 = linalg.generic {indexing_maps = [#map1, #map1, #map1], iterator_types = ["parallel", "parallel"]} ins(%3, %cst : tensor<6x3xf32>, tensor<6x3xf32>) outs(%4 : tensor<6x3xf32>) {
      ^bb0(%arg0: f32, %arg1: f32, %arg2: f32):  // no predecessors
        %10 = arith.addf %arg0, %arg1 : f32
        linalg.yield %10 : f32
      } -> tensor<6x3xf32>
      %6 = linalg.init_tensor [6, 3] : tensor<6x3xf32>
      %7 = linalg.generic {indexing_maps = [#map1, #map1], iterator_types = ["parallel", "parallel"]} ins(%5 : tensor<6x3xf32>) outs(%6 : tensor<6x3xf32>) {
      ^bb0(%arg0: f32, %arg1: f32):  // no predecessors
        %10 = math.floor %arg0 : f32
        linalg.yield %10 : f32
      } -> tensor<6x3xf32>
      %8 = linalg.init_tensor [6, 3] : tensor<6x3xi8>
      %9 = linalg.generic {indexing_maps = [#map1, #map1], iterator_types = ["parallel", "parallel"]} ins(%7 : tensor<6x3xf32>) outs(%8 : tensor<6x3xi8>) {
      ^bb0(%arg0: f32, %arg1: i8):  // no predecessors
        %10 = arith.fptosi %arg0 : f32 to i8
        linalg.yield %10 : i8
      } -> tensor<6x3xi8>
      util.global.store %9, @hoisted_0 : tensor<6x3xi8>
      util.initializer.return
    }
    util.initializer {
      %_params$1 = util.global.load @_params$1 : tensor<f32>
      %cst = arith.constant dense<1.270000e+02> : tensor<f32>
      %_params$0 = util.global.load @_params$0 : tensor<6x3xf32>
      %0 = linalg.init_tensor [6, 3] : tensor<6x3xf32>
      %1 = linalg.generic {indexing_maps = [#map1, #map1], iterator_types = ["parallel", "parallel"]} ins(%_params$0 : tensor<6x3xf32>) outs(%0 : tensor<6x3xf32>) {
      ^bb0(%arg0: f32, %arg1: f32):  // no predecessors
        %8 = math.abs %arg0 : f32
        linalg.yield %8 : f32
      } -> tensor<6x3xf32>
      %cst_0 = arith.constant 0xFF800000 : f32
      %2 = linalg.init_tensor [] : tensor<f32>
      %3 = linalg.fill(%cst_0, %2) : f32, tensor<f32> -> tensor<f32> 
      %4 = linalg.generic {indexing_maps = [#map1, #map0], iterator_types = ["reduction", "reduction"]} ins(%1 : tensor<6x3xf32>) outs(%3 : tensor<f32>) {
      ^bb0(%arg0: f32, %arg1: f32):  // no predecessors
        %8 = arith.maxf %arg0, %arg1 : f32
        linalg.yield %8 : f32
      } -> tensor<f32>
      %5 = linalg.init_tensor [] : tensor<f32>
      %hoisted = util.global.load @hoisted : tensor<f32>
      %6 = linalg.init_tensor [] : tensor<f32>
      %7 = linalg.generic {indexing_maps = [#map2, #map2, #map2], iterator_types = []} ins(%_params$1, %hoisted : tensor<f32>, tensor<f32>) outs(%6 : tensor<f32>) {
      ^bb0(%arg0: f32, %arg1: f32, %arg2: f32):  // no predecessors
        %8 = arith.mulf %arg0, %arg1 : f32
        linalg.yield %8 : f32
      } -> tensor<f32>
      util.global.store %7, @hoisted_1 : tensor<f32>
      util.initializer.return
    }
    util.global private @_params$0 = dense<[[0.000000e+00, 5.003000e+02, 1.000600e+03], [1500.8999, 2.001200e+03, 2.501500e+03], [3001.7998, 3502.09985, 4.002400e+03], [4502.69971, 5.003000e+03, 5.503300e+03], [6003.59961, 6503.8999, 7004.1997], [7.504500e+03, 8004.7998, 8.505100e+03]]> : tensor<6x3xf32>
    util.global private @hoisted : tensor<f32>
    util.global private @hoisted_0 : tensor<6x3xi8>
    util.global private @_params$1 = dense<5.000000e+00> : tensor<f32>
    util.global private @hoisted_1 : tensor<f32>
    func @get$hoisted() -> tensor<f32> {
      %hoisted = util.global.load @hoisted : tensor<f32>
      return %hoisted : tensor<f32>
    }
    func @get$hoisted_0() -> tensor<6x3xi8> {
      %hoisted_0 = util.global.load @hoisted_0 : tensor<6x3xi8>
      return %hoisted_0 : tensor<6x3xi8>
    }
    func @get$hoisted_1() -> tensor<f32> {
      %hoisted_1 = util.global.load @hoisted_1 : tensor<f32>
      return %hoisted_1 : tensor<f32>
    }
  }
```

**Comment by benvanik** [comment] 2021-12-16 05:20
global order matters (same with initializers) - you need to insert your globals prior to their first use

**Comment by stellaraccident** [comment] 2021-12-16 05:25
Ok, if this is the invariant, we should do something other than segfault if violated -- especially since this can be user provided, not just something within the compiler.

**Comment by benvanik** [comment] 2021-12-16 05:28
good point - doing it as a verifier is too expensive but we could have a global order verifier pass we could run inbetween major stages

**Comment by stellaraccident** [comment] 2021-12-16 05:29
I noted the assert that checks it. At a minimum, we should just add that and make it a soft failure of some kind.

**Comment by stellaraccident** [comment] 2021-12-16 05:29
But yeah, agreed on it being more explicit somewhere. This can and will happen (I've messed it up repeatedly).

**Comment by stellaraccident** [comment] 2021-12-16 05:33
Also, if we had a pass verifying it, it would be approximately the same amount of work to just fix the order too...

**Comment by benvanik** [comment] 2021-12-16 05:34
It's fine to have a verifier have a false negative - it's not fine for one that's load-bearing :)
(when we introduce indirect calls and such it gets really hard)

**Comment by ScottTodd** [comment] 2021-12-16 16:02
duplicate of https://github.com/google/iree/issues/6824?

**Comment by benvanik** [comment] 2021-12-16 16:24
yep!

**Closed by benvanik** 2021-12-16 16:24 UTC
Labels: compiler
