### ISSUE TITLE
Better bufferization for subtensor_insert

### ISSUE THREAD

**Issue by hanhanW** [google/iree#9363] opened 2022-06-07 14:57 UTC
We might not have the case in IREE, but I think it's worth to file an issue about it.

Input:

```mlir
module {
  func.func @subtensor_insert() {
    %0 = hal.interface.constant.load[0] : index
    %1 = hal.interface.constant.load[1] : index
    %2 = hal.interface.constant.load[2] : index
    %3 = hal.interface.constant.load[3] : index
    %4 = hal.interface.constant.load[4] : index
    %5 = hal.interface.constant.load[5] : index
    %6 = hal.interface.binding.subspan set(0) binding(0) type(storage_buffer) : !flow.dispatch.tensor<readonly:?x?xi32>{%0, %1}
    %7 = hal.interface.binding.subspan set(0) binding(1) type(storage_buffer) : !flow.dispatch.tensor<readonly:?x?xi32>{%2, %3}
    %8 = hal.interface.binding.subspan set(0) binding(2) type(storage_buffer) : !flow.dispatch.tensor<writeonly:?x?xi32>{%4, %5}
    %9 = flow.dispatch.tensor.load %6, offsets = [0, 0], sizes = [%0, %1], strides = [1, 1] : !flow.dispatch.tensor<readonly:?x?xi32>{%0, %1} -> tensor<?x?xi32>
    %10 = flow.dispatch.tensor.load %7, offsets = [0, 0], sizes = [%2, %3], strides = [1, 1] : !flow.dispatch.tensor<readonly:?x?xi32>{%2, %3} -> tensor<?x?xi32>
    %11 = tensor.insert_slice %9 into %10[3, 4] [%0, %1] [1, 1] : tensor<?x?xi32> into tensor<?x?xi32>
    flow.dispatch.tensor.store %11, %8, offsets = [0, 0], sizes = [%4, %5], strides = [1, 1] : tensor<?x?xi32> -> !flow.dispatch.tensor<writeonly:?x?xi32>{%4, %5}
    return
  }
}
```

Output:

```mlir
#map0 = affine_map<(d0, d1)[s0, s1] -> (d0 * s1 + s0 + d1)>                                                                   #map1 = affine_map<(d0, d1) -> (d0, d1)>
module {
  func.func @subtensor_insert() {
    %0 = hal.interface.constant.load[0] : index
    %1 = hal.interface.constant.load[1] : index
    %2 = hal.interface.constant.load[2] : index                                                                                   %3 = hal.interface.constant.load[3] : index
    %4 = hal.interface.constant.load[4] : index
    %5 = hal.interface.constant.load[5] : index
    %6 = hal.interface.binding.subspan set(0) binding(0) type(storage_buffer) : memref<?x?xi32>{%0, %1}
    %7 = hal.interface.binding.subspan set(0) binding(0) type(storage_buffer) : !flow.dispatch.tensor<readonly:?x?xi32>{%0, %1}
    %8 = hal.interface.binding.subspan set(0) binding(1) type(storage_buffer) : memref<?x?xi32>{%2, %3}
    %9 = hal.interface.binding.subspan set(0) binding(1) type(storage_buffer) : !flow.dispatch.tensor<readonly:?x?xi32>{%2, %3}
    %10 = hal.interface.binding.subspan set(0) binding(2) type(storage_buffer) : memref<?x?xi32>{%4, %5}
    %11 = hal.interface.binding.subspan set(0) binding(2) type(storage_buffer) : !flow.dispatch.tensor<writeonly:?x?xi32>{%4,%5}
    %12 = memref.subview %6[0, 0] [%0, %1] [1, 1] : memref<?x?xi32> to memref<?x?xi32, #map0>
    %13 = memref.subview %8[0, 0] [%2, %3] [1, 1] : memref<?x?xi32> to memref<?x?xi32, #map0>
    %14 = memref.alloc(%2, %3) : memref<?x?xi32>
    linalg.generic {indexing_maps = [#map1, #map1], iterator_types = ["parallel", "parallel"]} ins(%13 : memref<?x?xi32, #map0>) outs(%14 : memref<?x?xi32>) {
    ^bb0(%arg0: i32, %arg1: i32):
      linalg.yield %arg0 : i32
    }
    %15 = memref.subview %14[3, 4] [%0, %1] [1, 1] : memref<?x?xi32> to memref<?x?xi32, #map0>
    linalg.generic {indexing_maps = [#map1, #map1], iterator_types = ["parallel", "parallel"]} ins(%12 : memref<?x?xi32, #map0>) outs(%15 : memref<?x?xi32, #map0>) {
    ^bb0(%arg0: i32, %arg1: i32):
      linalg.yield %arg0 : i32
    }
    %16 = memref.subview %10[0, 0] [%4, %5] [1, 1] : memref<?x?xi32> to memref<?x?xi32, #map0>
    linalg.generic {indexing_maps = [#map1, #map1], iterator_types = ["parallel", "parallel"]} ins(%14 : memref<?x?xi32>) outs(%16 : memref<?x?xi32, #map0>) {
    ^bb0(%arg0: i32, %arg1: i32):
      linalg.yield %arg0 : i32
    }
    memref.dealloc %14 : memref<?x?xi32>
    return
  }
}
```

There is a alloc op to store temp values, and then we copy it to the destination buffer. In the old IREE bufferization, we're able to avoid the alloc op and use the destination buffer directly.

E.g.,

```mlir
// CHECK-LABEL: func.func @subtensor_insert()
//   CHECK-DAG:   %[[ARG0:.+]] = hal.interface.binding.subspan set(0) binding(0) type(storage_buffer)
//   CHECK-DAG:   %[[ARG1:.+]] = hal.interface.binding.subspan set(0) binding(1) type(storage_buffer)
//   CHECK-DAG:   %[[RET0:.+]] = hal.interface.binding.subspan set(0) binding(2) type(storage_buffer)
//   CHECK-DAG:   %[[D0:.+]] = hal.interface.constant.load[0] : index
//   CHECK-DAG:   %[[D1:.+]] = hal.interface.constant.load[1] : index
//       CHECK:   linalg.generic {{.*}} ins(%[[ARG1]] {{.*}} outs(%[[RET0]]
//       CHECK:   %[[SUBVIEW:.+]] = memref.subview %[[RET0]][3, 4] [%[[D0]], %[[D1]]] [1, 1]
//       CHECK:   linalg.generic {{.*}} ins(%[[ARG0]] {{.*}} outs(%[[SUBVIEW]]
```

**Comment by matthias-springer** [comment] 2022-06-08 07:47
By "old IREE bufferization" you mean before One-Shot Bufferize, right?

We have `initTensorElimination` in IREE, which will perform the optimization that you described (as a pre-processing pass to bufferization). The problem is that the buffer allocation is created during bufferization. I am currently working on an improvement of the bufferization (in MLIR core) that separates conflict resolution from bufferization. This should make it possible to get rid of the alloc here. It will still take a few days to get everything through review/land stuff.

**Comment by hanhanW** [comment] 2022-06-08 11:02
> By "old IREE bufferization" you mean before One-Shot Bufferize, right?

I meant the LinalgBufferize pass in IREE, which was developed by IREE team.

Good to know that it's on track. :)

**Comment by MaheshRavishankar** [comment] 2022-06-14 23:52
This pattern is indeed not seen in IREE anymore. `tensor.insert_slice` get fused with the `flow.dispatch.tensor.store` and copy only dispatches get bufferized early. I dont think it is worth moving that complexity into bufferization. So closing this issue.

**Closed** 2022-06-14 23:52 UTC
Labels: codegen
