### ISSUE TITLE
discord channel outdated

### ISSUE THREAD

**Issue by Joejiong** [google/iree#6571] opened 2021-07-28 07:16 UTC
discord channel outdated

**Comment by ScottTodd** [comment] 2021-07-28 15:23
Can you explain in more detail what the issue is? The Discord invite links in our README and on our website all still seem to be active to me.

**Comment by GMNGeoffrey** [comment] 2021-07-28 19:03
Yeah without more detail there's not much we can do here (note, I deleted the template boilerplate)

**Comment by benvanik** [comment] 2021-08-03 20:27
closing for now unless there's more details

**Closed by benvanik** 2021-08-03 20:27 UTC
Labels: bug 🐞, help wanted, invalid 🤷‍♀️
