### ISSUE TITLE
Flow ExStreamFragmentOp does not round-trip cleanly

### ISSUE THREAD

**Issue by stellaraccident** [google/iree#6185] opened 2021-06-11 06:19 UTC
Issue appears to be in the parser for result types. Found by trying to reduce a test case from `-print-ir-after-all` and getting a parse error trying to run it through opt.

```
  func @Reshape__3x2x2x2__f32__uniform__target_shape_2_1_4_1(%arg0: !hal.buffer_view) -> !hal.buffer_view attributes {iree.abi.stub, iree.module.export, iree.reflection = {iree.abi = "{\22a\22:[[\22ndarray\22,\22f32\22,4,3,2,2,2]],\22r\22:[[\22ndarray\22,\22f32\22,5,3,2,1,4,1]],\22v\22:1}"}} {
    %0 = hal.tensor.cast %arg0 : !hal.buffer_view -> tensor<3x2x2x2xf32>
    %1 = flow.ex.stream.fragment(%0) : (tensor<3x2x2x2xf32>) -> %0 =
        (%arg1: tensor<3x2x2x2xf32>) -> tensor<3x2x1x4x1xf32> {
      %3 = flow.tensor.reshape %arg1 : tensor<3x2x2x2xf32> -> tensor<3x2x1x4x1xf32>
      flow.return %3 : tensor<3x2x1x4x1xf32>
    }
    %2 = hal.tensor.cast %1 : tensor<3x2x1x4x1xf32> -> !hal.buffer_view
    return %2 : !hal.buffer_view
  }
```

If running through opt, this reports:

```
../iree/iree/compiler/Dialect/HAL/Conversion/StandardToHAL/test/structural_ops.mlir:31:26: error: use of value '%1' expects different type than prior uses: 'tensor<3x2x1x4x1xf32>' vs 'tensor<3x2x2x2xf32>'
    %2 = hal.tensor.cast %1 : tensor<3x2x1x4x1xf32> -> !hal.buffer_view
                         ^
../iree/iree/compiler/Dialect/HAL/Conversion/StandardToHAL/test/structural_ops.mlir:26:5: note: prior use here
    %1 = flow.ex.stream.fragment(%0) : (tensor<3x2x2x2xf32>) -> %0 =
```

Removing %2 and just returning %arg0 directly allows it to parse print and we find that the result type is in fact changed to `tensor<3x2x2x2xf32>` as the error reports.

**Comment by stellaraccident** [comment] 2021-06-11 06:30
Actually this looks like a not-legal representation for the tied operands.

**Comment by stellaraccident** [comment] 2021-06-11 06:35
I updated my test case to not tie operands but leaving this open because in this example, we seem to be generating an illegal op.

```
    %1 = flow.ex.stream.fragment(%0) : (tensor<3x2x2x2xf32>) -> (tensor<3x2x1x4x1xf32>) =
        (%arg1: tensor<3x2x2x2xf32>) -> tensor<3x2x1x4x1xf32> {
      %3 = flow.tensor.reshape %arg1 : tensor<3x2x2x2xf32> -> tensor<3x2x1x4x1xf32>
      flow.return %3 : tensor<3x2x1x4x1xf32>
    }
```

**Comment by benvanik** [comment] 2021-06-11 15:39
Duplicate of #6075. We can disable the TieStreamResults pattern in FlowOpFolders.cpp to avoid the ties.

**Closed by benvanik** 2021-06-11 15:39 UTC
