### ISSUE TITLE
mnist_training Colab notebook fails on latest releases

### ISSUE THREAD

**Issue by ScottTodd** [google/iree#6163] opened 2021-06-09 21:48 UTC
**Describe the bug**
The [`mnist_training.ipynb`](https://github.com/google/iree/blob/main/colab/mnist_training.ipynb) Colab notebook ( [![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/google/iree/blob/main/colab/mnist_training.ipynb) ) is currently failing. From what I can tell it was last ran when it was checked in as part of https://github.com/google/iree/pull/4526, and it has otherwise just been updated with simple find/replaces.

We've been using `%%capture` around the pip install, so I can't see which release the notebook was using when it last ran :/ maybe we should drop that?

**To Reproduce**

1. Open the notebook
2. Connect to a default runtime and run all cells
3. Observe error when running in this cell:

```python
# Compile the TrainableDNN module
compiled_model = module_utils.IreeCompiledModule.create_from_class(
    TrainableDNN, 
    module_utils.BackendInfo(backend_choice), 
    exported_names=exported_names)
```

salient error logs (will require dropping down a level to get more useful information):

```
CompilerToolError: Error invoking IREE compiler tool iree-import-tf
Diagnostics:
2021-06-09 21:40:05.678406: I external/org_tensorflow/tensorflow/cc/saved_model/bundle_v2.cc:37] Reading SavedModel from: /tmp/tmpdimx7a85.sm
2021-06-09 21:40:05.680001: I external/org_tensorflow/tensorflow/cc/saved_model/bundle_v2.cc:60] Reading SavedModel debug info (if present) from: /tmp/tmpdimx7a85.sm
2021-06-09 21:40:05.745176: I external/org_tensorflow/tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE3 SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
TensorFlow crashed, please file a bug on https://github.com/tensorflow/tensorflow/issues with the trace below.
Stack dump:
0.	Program arguments: /usr/local/lib/python3.7/dist-packages/iree/tools/tf/iree-import-tf /tmp/tmpdimx7a85.sm --tf-import-type=savedmodel_v2 --tf-savedmodel-exported-names=predict,learn --tf-savedmodel-tags= --mlir-print-debuginfo
```

**Additional context**
We have some tests using training at https://github.com/google/iree/tree/main/integrations/tensorflow/e2e/keras/train that I believe are still running/passing. Not sure how different those are from what this notebook does.

cc @stellaraccident @MaheshRavishankar @phoenix-meadowlark

**Comment by kintel** [comment] 2021-06-18 15:52
This was caused by a bad snapshot release and should be fixed now.

To prove this, I installed IREE as of 9 days ago using the following install command and got the same error as you:
`!python -m pip install iree-compiler-snapshot iree-runtime-snapshot iree-tools-tf-snapshot --find-links https://github.com/google/iree/releases/tag/snapshot-20210608.328`

The current default install works fine. If this happens again in the future, you can force-install an older snapshot using the above command-line and browse releases at https://github.com/google/iree/releases

**Comment by ScottTodd** [comment] 2021-06-18 16:03
Oh, that's great news! Thanks for checking :D

I'm adding some automated test coverage for the notebooks (see https://github.com/google/iree/issues/6165) that will help spot this sooner, but we should also add more direct test coverage as this stabilizes more.

We have _some_ tests here, but note that most are expected to be failing: https://github.com/google/iree/blob/4d3b33a0f3e9a5d9266463efbafb6cb2be9e3251/integrations/tensorflow/e2e/keras/train/CMakeLists.txt#L15-L44

**Closed** 2021-06-18 16:03 UTC
Labels: bug 🐞, integrations/colab, integrations/tensorflow
