### ISSUE TITLE
Reuse the same flow.variable if they are identical

### ISSUE THREAD

**Issue by hanhanW** [google/iree#3618] opened 2020-10-27 07:32 UTC
In `-iree-mlir-to-benchmark-vm-bytecode-module`, we could see something like:

```
  flow.variable @_large_const_0 dense<0.000000e+00> : tensor<5x3xf32> attributes {noinline, sym_visibility = "private"}
  flow.variable @_large_const_1 dense<0.000000e+00> : tensor<3x5xf32> attributes {noinline, sym_visibility = "private"}
  flow.variable @_large_const_2 dense<0.000000e+00> : tensor<3x5xf32> attributes {noinline, sym_visibility = "private"}
  flow.variable @_large_const_3 dense<0.000000e+00> : tensor<5x5xf32> attributes {noinline, sym_visibility = "private"}
  flow.variable @_large_const_4 dense<0.000000e+00> : tensor<5x3xf32> attributes {noinline, sym_visibility = "private"}
  flow.variable @_large_const_5 dense<0.000000e+00> : tensor<3x5xf32> attributes {noinline, sym_visibility = "private"}
```

I think it's possible and good if we can reuse the same one if they are identical.

**Comment by benvanik** [comment] 2020-10-27 11:01
This is a duplicate of #1144.

**Closed by benvanik** 2020-10-27 11:01 UTC
Labels: compiler, duplicate, enhancement
