### ISSUE TITLE
Support inlining small constants into dispatch regions

### ISSUE THREAD

**Issue by benvanik** [google/iree#4897] opened 2021-02-20 01:26 UTC
Today we only inline splat constants (`constant dense<5> : tensor<4xi32>`), via the logic here:
https://github.com/google/iree/blob/main/iree/compiler/Dialect/Flow/Transforms/RematerializeDispatchConstants.cpp#L41-L57

This excludes things like like `constant dense<[0,1,2,3]> : tensor<4xi32>` or `constant dense<[1.0, 2.0]> : tensor<2xf32>`. As part of buffer allocation I'm noticing a large number of small constants that then aren't getting inlined and thus need to be planned for externally and passed in. We're talking specifically about reasonable constants to inline, not MB-sized things. Think more like 16-element lookup tables, initialization vectors, channel masks, etc.

Since SPIR-V and LLVM both support constants this may just be a missing conversion or two between what we are taking in (mhlo on the old path, linalg on the new path) and those targets.

Mahesh says:
`We should be able to use tensor_to_memref here to wire things together and finally SPIRV and LLVM should handle the constant`

This can be tested by changing the isSplatConstant to return true if the DenseElementsAttr logic is changed to:
```c++
  } else if (auto value = constantOp.getValue().dyn_cast<DenseElementsAttr>()) {
    auto shapedType = constantOp.getType().cast<ShapedType>();
    uint64_t estimatedByteLength =
        (shapedType.getNumElements() * shapedType.getElementTypeBitWidth()) / 8;
    return denseAttr.isSplat() ||
           estimatedByteLength <= 256;  // or whatever
  } else {
```

That should cause the constants to end up in the dispatch regions. Here's an example dispatch region that fails today (masking from a clamp or something) with the above change:
```mlir
func @test() -> tensor<5xi32> {
  %c5 = constant 5 : index
  %3 = iree.unfoldable_constant dense<4.0> : tensor<f32>
  %4 = flow.dispatch.region[%c5 : index](%arg2 = %3 : tensor<5xf32>) -> (tensor<5xi32>) {
    %cst_4 = constant dense<0.000000e+00> : tensor<5xf32>
    %49 = "mhlo.compare"(%arg2, %cst_4) {comparison_direction = "EQ"} : (tensor<5xf32>, tensor<5xf32>) -> tensor<5xi1>
    %50 = "mhlo.convert"(%49) : (tensor<5xi1>) -> tensor<5xi32>
    %cst_5 = constant dense<[1, 2, 3, 4, 5]> : tensor<5xi32>
    %51 = mhlo.multiply %50, %cst_5 : tensor<5xi32>
    flow.return %51 : tensor<5xi32>
  }
  return %4 : tensor<5xi32>
}
```

**Comment by MaheshRavishankar** [comment] 2021-02-20 20:58
@hanhanW temporarily passing this to you (ill pick it up later in the week if you dont get to it by then). Adding support on the existing codegen path (i.e. not linalg on tensors) would require two steps

1) Adding a patter to convert `std.constant` to `std.constant -> tensor_to_memref` in HLOToLinalgOnBuffers
2) Handling `tensor_to_memref` in SPIR-V lowering (basicall iy is a no-op but needs to have the pattern for it.

Ill add the support on the linalg on tensors path

**Comment by hanhanW** [comment] 2021-02-21 12:54
Is the idea to convert below snippet

```mlir
module {
  func @small_cst() {
    %c0 = constant 0 : index
    %0 = hal.interface.load.tensor @legacy_io::@arg0, offset = %c0 : tensor<5xi32>
    %1 = constant dense<[1, 2, 3, 4, 5]> : tensor<5xi32>
    %2 = mhlo.add%0, %1 : tensor<5xi32>
    hal.interface.store.tensor %2, @legacy_io::@ret0, offset = %c0 : tensor<5xi32>
    return
  }
  hal.interface @legacy_io attributes {sym_visibility = "private"} {
    hal.interface.binding @arg0, set=0, binding=0, type="StorageBuffer", access="Read"
    hal.interface.binding @ret0, set=0, binding=1, type="StorageBuffer", access="Write"
  }
}
```

to

```mlir
#map = affine_map<(d0) -> (d0)>
module  {
  func @small_cst() {
    %0 = iree.placeholder for "interface buffer" {binding = @legacy_io::@ret0} : memref<5xi32>
    %c0 = constant 0 : index
    %1 = iree.placeholder for "interface buffer" {binding = @legacy_io::@arg0} : memref<5xi32>
    %2 = constant dense<[1, 2, 3, 4, 5]> : tensor<5xi32>
    %3 = tensor_to_memref %2 : memref<5xi32>
    linalg.generic {indexing_maps = [#map, #map, #map], iterator_types = ["parallel"]} ins(%1, %3 : memref<5xi32>, memref<5xi32>) outs(%0 : memref<5xi32>) {
    ^bb0(%arg0: i32, %arg1: i32, %arg2: i32):  // no predecessors
      %4 = addi %arg0, %arg1 : i32
      linalg.yield %4 : i32
    }
    return
  }
  hal.interface @legacy_io attributes {sym_visibility = "private"} {
    hal.interface.binding @arg0, set=0, binding=0, type="StorageBuffer", access="Read"
    hal.interface.binding @ret0, set=0, binding=1, type="StorageBuffer", access="Write"
  }
}
```

And drop `TensorToMerefOp` in ConvertToSPIRVPass (like linalg::TensorReshapeOp)?

**Comment by MaheshRavishankar** [comment] 2021-02-21 14:11
I guess by drop it you mean just forward the `!spv.array`. Yes, thats what I mean. We can just add this pattern to core..

**Comment by hanhanW** [comment] 2021-02-22 06:02
Yes, I meant to forward the `spv.array` by replacing the op with operands, like:

https://github.com/google/iree/blob/87d169a59bc6203b8e2813438d9b3a835fbe05da/iree/compiler/Conversion/LinalgToSPIRV/ConvertToSPIRVPass.cpp#L275-L287

**Comment by MaheshRavishankar** [comment] 2021-02-22 17:07
Right!

**Comment by MaheshRavishankar** [comment] 2021-02-23 20:12
@hanhanW did you already get to this. I am hitting this on some unrelated change but might as well fix it. Just looking to fix it on the linalg on tensors path though for now. Let me know.

**Comment by hanhanW** [comment] 2021-02-23 20:13
No, I haven't started the work yet.

**Comment by MaheshRavishankar** [comment] 2021-02-23 20:16
Ok, ill update here if I get this working on the linalg on tensors path.

**Comment by MaheshRavishankar** [comment] 2021-03-05 00:56
Started looking into this on the linalg on tensors path briefly (WIP commit here https://github.com/MaheshRavishankar/iree/commit/489d97c47feeb374742484f42d840b5567cb909c). 

It stumped right now cause a canonicalizer in core takes a `constant -> tensor_to_memref -> load` and converts it into `constant -> tensor.extract`. Which might be OK. It means `tensor.extract` needs to be supported now in Standard/Tensor SPIR-V now. See dump IR after all [here ](https://gist.github.com/MaheshRavishankar/f3d0fe7a33e37ffe93fa585d0154f7be)

On the LLVM side it looks there is a tensor-constant-bufferize pass  ([here](https://github.com/llvm/llvm-project/blob/9c0274cdeae904089806be6faee72b9126d2cf5b/mlir/include/mlir/Dialect/StandardOps/Transforms/Passes.td#L52)) that we might need to use, but that might work out of the box.

Leaving notes here if someone else has time to pick this up and finish. I am going to be switching to some higher priority tasks for a bit.

**Comment by antiagainst** [comment] 2021-03-05 14:14
I see we are extracting from constant using dynamic indices. Then for SPIR-V we need to create local variables to hold the constant and then use access chain, which supports dynamic indices. I can throw in a pattern for it.

**Comment by MaheshRavishankar** [comment] 2021-03-05 17:07
I think constants as variables (i forget the scope now) are already supported in SPIR-V backend. What doesnt seem to be supported yet is `tensor.extract`?

**Comment by antiagainst** [comment] 2021-03-05 18:08
Not really. We have patterns to convert tensor `std.constant`into `!spv.array` `spv.Constant`. Putting the generated constant in variables is not supported. It's not a general applicable pattern anyway; normally we don't want to do that as large tensor should just go through external buffers instead of living in a local variable.

**Comment by benvanik** [comment] 2021-03-05 18:11
That's not what this is about - this is precisely about the cases where we *don't* want to go through buffers: it's a totally supported and well-known use to embed small constants into shaders. It is never a good idea to use generic memory accesses for loading 2 constant floats or 4 constant bytes.

**Comment by antiagainst** [comment] 2021-03-05 18:23
Yup, I understand that and what this issue is for. Not saying that we shouldn't do this for small constant tensors. Actually https://reviews.llvm.org/D98052. :) My previous comment is trying to explain why there is no general patterns to put converted constants in variables right now and saying there is a threshold for this.

**Comment by MaheshRavishankar** [comment] 2021-03-12 06:10
This is now a blocker for getting mobilebert running on the new path (Cause new changes to Flow dialect leads to failures if this case is not handled. Better to fix this case now instead of tracking the failures.

This is my WIP commit : https://github.com/MaheshRavishankar/iree/commit/4a476fc9bd2c520041773edb08de897282e76811
This requires https://reviews.llvm.org/D98478 
Things work on CPU, but on GPU side we have an interesting issue

`std.constant` are lowered to `!spv.array`, but when lowering the `std.constant -> tensor_to_memref -> load ` chain, the load expects a `!spv.ptr<!spv.struct<!spv.array ...> >`. So the lowering fails. Here is the repro for this issue

```
module attributes {spv.target_env = #spv.target_env<#spv.vce<v1.3, [Shader, GroupNonUniform, GroupNonUniformVote, GroupNonUniformArithmetic, GroupNonUniformBallot, GroupNonUniformShuffle, GroupNonUniformShuffleRelative], [SPV_KHR_storage_buffer_storage_class]>, SwiftShader:CPU, {c\
ooperative_matrix_properties_nv = [], max_compute_shared_memory_size = 16384 : i32, max_compute_workgroup_invocations = 128 : i32, max_compute_workgroup_size = dense<[128, 128, 64]> : vector<3xi32>, subgroup_size = 4 : i32}>}  {
  func @cst_plus_tensor_dispatch_0() attributes {spv.entry_point_abi = {local_size = dense<[32, 1, 1]> : vector<3xi32>}} {
    %c0 = constant 0 : index
    %c2_i32 = constant 2 : i32
    %cst = constant dense<[[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]> : tensor<2x2x3xi32>
    %c12 = constant 12 : index
    %c6 = constant 6 : index
    %c3 = constant 3 : index
    %0 = tensor_to_memref %cst : memref<2x2x3xi32>
    %1 = hal.interface.binding.subspan @legacy_io::@ret0[%c0] : memref<2x2x3xi32>
    %2 = "gpu.block_id"() {dimension = "x"} : () -> index
    %3 = "gpu.block_dim"() {dimension = "x"} : () -> index
    %4 = "gpu.thread_id"() {dimension = "x"} : () -> index
    %5 = muli %2, %3 : index
    %6 = addi %5, %4 : index
    %7 = cmpi slt, %6, %c12 : index
    scf.if %7 {
      %8 = divi_signed %6, %c6 : index
      %9 = remi_signed %6, %c6 : index
      %10 = divi_signed %9, %c3 : index
      %11 = remi_signed %9, %c3 : index
      %12 = load %0[%8, %10, %11] : memref<2x2x3xi32>
      %13 = muli %12, %c2_i32 : i32
      store %13, %1[%8, %10, %11] : memref<2x2x3xi32>
    }
    return
  }
  hal.interface @legacy_io attributes {sym_visibility = "private"} {
    hal.interface.binding @ret0, set=0, binding=0, type="StorageBuffer", access="Write|Discard"
  }
}
```

The lowered function just before it fails

```
spv.func @cst_plus_tensor_dispatch_0() "None" attributes {spv.entry_point_abi = {local_size = dense<[32, 1, 1]> : vector<3xi32>}} {
  %0 = spv.Constant 0 : i32
  %c0 = constant 0 : index
  %1 = spv.Constant 2 : i32
  %c2_i32 = constant 2 : i32
  %2 = spv.Constant dense<[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]> : tensor<12xi32> : !spv.array<12 x i32, stride=4>
  %cst = constant dense<[[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]> : tensor<2x2x3xi32>
  %3 = spv.Constant 12 : i32
  %c12 = constant 12 : index
  %4 = spv.Constant 6 : i32
  %c6 = constant 6 : index
  %5 = spv.Constant 3 : i32
  %c3 = constant 3 : index
  %6 = tensor_to_memref %cst : memref<2x2x3xi32>
  %7 = hal.interface.binding.subspan @legacy_io::@ret0[%c0] : memref<2x2x3xi32>
  %8 = "gpu.block_id"() {dimension = "x"} : () -> index
  %9 = "gpu.block_dim"() {dimension = "x"} : () -> index
  %10 = "gpu.thread_id"() {dimension = "x"} : () -> index
  %11 = muli %8, %9 : index
  %12 = addi %11, %10 : index
  %13 = cmpi slt, %12, %c12 : index
  scf.if %13 {
    %14 = divi_signed %12, %c6 : index
    %15 = remi_signed %12, %c6 : index
    %16 = divi_signed %15, %c3 : index
    %17 = remi_signed %15, %c3 : index
    %18 = load %6[%14, %16, %17] : memref<2x2x3xi32>
    %19 = muli %18, %c2_i32 : i32
    store %19, %7[%14, %16, %17] : memref<2x2x3xi32>
  }
  return
}
```

@antiagainst @hanhanW any thoughts on how to proceed here?

**Comment by hanhanW** [comment] 2021-03-12 10:14
Throwing out some ideas. How about running a pass before converting to SPIR-V?

We can create a tensor_load op to turn it back to a tensor. Then we rewrite load op to tensor.extract op if the operand type is tensor. After that, we can go with StandardToSPIRV pass. It will create a spirv::VariableOp for the spirv::ConstantOp and load the value from it.

See https://github.com/llvm/llvm-project/blob/cfe8f8e0f010077f5942bce88a2fd331b90ccea7/mlir/lib/Conversion/StandardToSPIRV/StandardToSPIRV.cpp#L551-L566

**Comment by antiagainst** [comment] 2021-03-12 12:26
Actually the pattern in https://github.com/google/iree/issues/4897#issuecomment-797260661 is what I'd expect: we have a `tensor_to_memref` to write the constant to a variable and the load from it. In the previous https://github.com/google/iree/issues/4897#issuecomment-791063522 we have the `tensor_to_memref` but it's effectively dead code because we go back and `tensor.extract` from the original constant.

I think we can throw in a pattern to lower `tensor_to_memref` to creating and initializing to a local variable. Then the load and other actions will follow naturally. (The `memref` memory space is interesting here. But at the moment we basically don't use any other memref namespace in upper layers other than 0 thus far anyway. So choosing the suitable one, here `Function`, when lowering to SPIR-V sounds reasonable to me.)

**Comment by antiagainst** [comment] 2021-03-12 14:25
Yeah, the`memref` namespace will be an issue. It actually roots in a long-lasting problem: the type conversion is op-agnostic. The causes the upstream bufferization [always create](https://github.com/llvm/llvm-project/blob/774f1d3ffd458d6cb82d5039758ef1cf6370957f/mlir/lib/Transforms/Bufferize.cpp#L45) `memref` using memory space 0, and in SPIR-V we [always convert](https://github.com/llvm/llvm-project/blob/bb6f5c8314799a6553829b724c649e825a558caf/mlir/lib/Dialect/SPIRV/Transforms/SPIRVConversion.cpp#L111) `memref` with memory space 0 to `StorageBuffer`. The local decision to convert `memref` for holding a small constant array into `Function` storage class will run in conflict with the dialect conversion framework, which legalizes `std.load`'s first operand to `StorageBuffer` before converting the op. A proper fix for this is either have the type conversion taking op into consideration, or probably have a pass before to reassign `memref` memory space (which is useful for [adopting symbolic namespace](https://bugs.llvm.org/show_bug.cgi?id=49507) too). But here we have our own bufferization pass. Like `WorkgroupMemoryAllocationFn`, we can provide an additional parameter to supply the memory space for the `tensor_to_memref`-created `memref`.

**Comment by MaheshRavishankar** [comment] 2021-03-12 21:19
SOrry for the delayed response, was working through some issues. Posting current approach I am taking.

The core issue is `(load (tensor_to_memref $value) $indices)` being converted to `tensor_extract $value $indices)`. This is a canonicalization pattern. So after bufferization running canonicalization makes this pattern kick in.
Personally this pattern is flawed cause it is
1) Undoing bufferization
2) Even worse is that it is actually not checking that there are no stores to the result of the `tensor_to_memref` before applying this pattern.
Discussion with other folks, I havent been able to convince them that this pattern should be removed (or be made reduced scope). There seems to be some inherent semantics w.r.t to `tensor_to_memref` that is being used to justify issue (2).

So leaving that aside, the use of `tensor_to_memref` here is fine cause we are only using it "bufferize constants" that will never be stored to. So actually keeping that canonicalization pattern works fine for the SPIR-V side.

THe issue now is on the LLVM side. There is a pass to convert `constant` into module level symbols which is of `memref` type. This canonicalization interferes with that. So for now, just planning to undo the canonicalization on the LLVM path and that should make everything work. Going for this now, cause then we dont need anything fixed on the MLIR side (even though the core semantics flaw of the canonicalization pattern exists).

**Comment by MaheshRavishankar** [comment] 2021-03-15 19:54
PR #5098 added support for most part, but didnt go all the way cause there seems to be a correctness issue on LLVM side.
Uncommenting the lines [here](https://github.com/google/iree/blob/fa382fb3b72c18ea155473cd093b2c2a3386ce1d/iree/compiler/Dialect/Flow/IR/FlowOps.cpp#L828)

```
      // TODO(GH-4897): Non-splat constants seems to have an issue on the LLLVM
      // side. Uncomment after that is fixed.
      // auto shapedType = constantOp.getType().cast<ShapedType>();
      // uint64_t estimatedByteLength =
      //     (shapedType.getNumElements() * shapedType.getElementTypeBitWidth())
      //     / 8;
      return denseAttr
          .isSplat();  // || estimatedByteLength <= 256;  // or whatever
```

to 

```
      auto shapedType = constantOp.getType().cast<ShapedType>();
      uint64_t estimatedByteLength =
          (shapedType.getNumElements() * shapedType.getElementTypeBitWidth())
          / 8;
      return denseAttr.isSplat() || estimatedByteLength <= 256;
```

makes the fullyconnected e2e test fails with Linalg on tensors path on CPU (the GPU side still passes).
The compiled code looks fine to me ([dump after all](https://gist.github.com/MaheshRavishankar/eebe7ccf27a3089deba348a28b4c2050)).

Passing to @asaadaldien

**Comment by asaadaldien** [comment] 2021-03-16 19:49
The problem is in `IREE::HAL::LinkExecutablesPass` it merges all constant into one. See the following test case/full IR
https://gist.github.com/asaadaldien/3da93ce78d8c3523920e8dd345c1a8ba

**Comment by MaheshRavishankar** [comment] 2021-03-16 20:04
Oh nice catch! And this is not run on the SPIR-V path, so it passes. Make sense

**Comment by MaheshRavishankar** [comment] 2021-03-16 20:18
Passing back to Ben for issue Ahmed pointed to above.

**Comment by MaheshRavishankar** [comment] 2021-03-17 05:23
I looked into this a little bit more. Thanks @asaadaldien  for the IR dump.

@ScottTodd tagging you here cause the issue is related to a TODO with your name on it [here](https://github.com/google/iree/blob/f9cda5a7708255b0984d3c63cbef1c1ee3001abb/iree/compiler/Dialect/HAL/Target/TargetBackend.cpp#L117) . THe two constants in the program above are lowered to module-level symbols that happen to have the same name. When one of them gets instantiated in the linked module the other one gets dropped. Using analogy of traditional linkers, this is marked a private symbol. So its not really a name clash here on linking. For a private symbol I guess these would have to be renamed to disambiguate instead of just dropping one. Also for public symbols this should raise an error.

I am not expert on linking, so there might be a more nuanced solution here. Thoughts?

**Comment by benvanik** [comment] 2021-03-17 07:31
good catch! You are correct that linking should rename any symbols in the modules with the same name. There's some utils in SymbolTable for doing name unique-ing automatically but I think we want to handle it with a comparison for equality first and could do it ourselves.

**Comment by ScottTodd** [comment] 2021-03-17 15:26
Ah... yeah. We could check for equality with these functions: https://github.com/google/iree/blob/a6a827784b0726c5a9e702d1af1a51379cd8f975/iree/compiler/Dialect/Flow/Transforms/DeduplicateExecutables.cpp#L47-L50
(which could be upstreamed, see https://github.com/google/iree/issues/3996)

That [gist](https://gist.github.com/asaadaldien/3da93ce78d8c3523920e8dd345c1a8ba) has multiple constants named `__constant_2x2xf32` with different values:
```
        llvm.mlir.global private constant @__constant_2x2xf32(dense<[[1.000000e+00, 2.000000e+00], [3.000000e+00, 4.000000e+00]]> : tensor<2x2xf32>) : !llvm.array<2 x array<2 x f32>>
```
```
        llvm.mlir.global private constant @__constant_2x2xf32(dense<[[4.000000e+00, 5.000000e+00], [6.000000e+00, 7.000000e+00]]> : tensor<2x2xf32>) : !llvm.array<2 x array<2 x f32>>
```

**Comment by asaadaldien** [comment] 2021-03-17 15:32
We can also use the renaming utils as Ben mentioned and CSE after the linking which will remove globas with the same values.

**Comment by MaheshRavishankar** [comment] 2021-03-17 16:08
Awesome! Seems like we have options. Lets chat in a more group setting to come to a consensus on way forward.

**Comment by benvanik** [comment] 2021-03-17 16:16
> We can also use the renaming utils as Ben mentioned and CSE after the linking which will remove globas with the same values.

does CSE handle LLVM globals? I think it needs a dedicated pass that doesn't exist - that's one of the reasons we have DeduplicateExecutables. If we can prevent the duplicates from being inserted in the first place that'd be best.

**Comment by MaheshRavishankar** [comment] 2021-03-19 06:41
Tried this out [here](https://github.com/MaheshRavishankar/iree/commit/7d3baeb0bd7fa0d8402daf1a3cefee8552a6b8f4). Unfortunately it turns out this is a bit more complex than I thought it was. The "private" you see on the symbols before `LinkExecutablesPass` in the gist posted [above](https://github.com/google/iree/issues/4897#issuecomment-800556941) is actually the symbol in LLVM dialect and not the MLIR symbol visibility. So that makes things more involved cause it seems like those are actually not marked as "Private" symbols in MLIR. There needs to be some way of mapping the LLVM symbol visibility to MLIR symbol visibility, which probably requires some discussion and cant be done as a quick fix. 

So wondering if we should disable this linking of executables (like it is done on the SPIR-V side) till this can be resolved. Note that this is the issue possibly happening in #5152.

**Comment by asaadaldien** [comment] 2021-03-19 16:05
Thanks @MaheshRavishankar for giving this a shot, linking executables is very important for perf and its analysis...
Another **short term** fix is to add pass after `TensorConstantBufferize` to alter `global_memref` sym_name and append func names so we will have `__constant_2x2xf32_foo_dispatch_1`, `__constant_2x2xf32_foo_dispatch_2`.

**Comment by MaheshRavishankar** [comment] 2021-03-19 16:09
Ok, I'll see if I can add this to the upstream pass, though there might be push back against it (Which would be valid, but it is a small change). I'll take a stab at it.

**Comment by asaadaldien** [comment] 2021-03-19 16:16
Thanks @MaheshRavishankar , If there is a push back for `sym_names` in upstream we can add another Module [pass](https://github.com/google/iree/blob/main/iree/compiler/Conversion/LinalgToLLVM/Passes.cpp#L65) here that does rename `memref_global` symbol names.
IMO the real long term fix is to get the symbol_table rename you linked [above  ](https://github.com/MaheshRavishankar/iree/commit/7d3baeb0bd7fa0d8402daf1a3cefee8552a6b8f4)

**Comment by benvanik** [comment] 2021-03-19 16:24
It'd be nice if private LLVM-dialect symbols responded to the same symbol trait queries as any other dialect - may call for an interface (if one doesn't exist already) so that dialects can map things. That said, the linking phase is HAL target-specific and we could perform whatever logic we wanted as part of that - such as a cleanup of duplicated global_memref symbols post-linking (as we could run prior to verification and handle the name conflicts ourselves).

**Comment by benvanik** [comment] 2021-03-19 16:27
linking happens here: https://github.com/google/iree/blob/98f2135ed300be57145c705ebe3a14b9641452ef/iree/compiler/Dialect/HAL/Target/LLVM/LLVMAOTTarget.cpp#L114-L117
we can do the cleanup prior to returning

**Comment by MaheshRavishankar** [comment] 2021-03-19 16:35
Thanks for the pointer. I am just going to try to do that there now, cause that is the cleanest solution I can see.

**Closed** 2021-03-19 21:03 UTC
Labels: codegen, performance ⚡
