### ISSUE TITLE
SPIR-V compilation crash on return of i1

### ISSUE THREAD

**Issue by stellaraccident** [google/iree#2050] opened 2020-05-28 23:04 UTC
I tickled this while fiddling with dispatch region fusion such that a dispatch region returns an i1 (instead of the more common case where a compare gets fused into something else). I suspect it can be repro'd by just compiling a standalone compare op.

Input to SPIR-V compilation:
```
// *** IR Dump Before mlir::iree_compiler::(anonymous namespace)::ConvertToSPIRVPass ***
module attributes {spv.target_env = #spv.target_env<#spv.vce<v1.3, [Shader], [SPV_KHR_storage_buffer_storage_class]>, {max_compute_workgroup_invocations = 128 : i32, max_compute_workgroup_size = dense<[128, 128, 64]> : vector<3xi32>}>} {
  func @mod_ex_dispatch_0() attributes {spv.entry_point_abi = {local_size = dense<[32, 1, 1]> : vector<3xi32>}} {
    %cst = constant 0.000000e+00 : f32
    %cst_0 = constant 2.000000e+00 : f32
    %c4 = constant 4 : index
    %c32 = constant 32 : index
    %c-1 = constant -1 : index
    %0 = iree.placeholder for "interface buffer" {binding = @legacy_io::@ret0} : memref<4xf32>
    %1 = iree.placeholder for "interface buffer" {binding = @legacy_io::@ret1} : memref<4xi1>
    %2 = iree.placeholder for "interface buffer" {binding = @legacy_io::@ret2} : memref<4xi1>
    %3 = iree.placeholder for "interface buffer" {binding = @legacy_io::@ret3} : memref<4xf32>
    %4 = iree.placeholder for "interface buffer" {binding = @legacy_io::@arg0} : memref<4xf32>
    %5 = "gpu.block_id"() {dimension = "x"} : () -> index
    %6 = "gpu.grid_dim"() {dimension = "x"} : () -> index
    %7 = muli %5, %c32 : index
    %8 = muli %6, %c32 : index
    scf.for %arg0 = %7 to %c4 step %8 {
      %9 = muli %arg0, %c-1 : index
      %10 = addi %9, %c4 : index
      %11 = cmpi "slt", %c32, %10 : index
      %12 = select %11, %c32, %10 : index
      %13 = "gpu.thread_id"() {dimension = "x"} : () -> index
      %14 = "gpu.block_dim"() {dimension = "x"} : () -> index
      scf.for %arg1 = %13 to %12 step %14 {
        %15 = addi %arg0, %arg1 : index
        %16 = load %4[%15] : memref<4xf32>
        %17 = remf %16, %cst_0 : f32
        store %17, %0[%15] : memref<4xf32>
      }
    }
    scf.for %arg0 = %7 to %c4 step %8 {
      %9 = muli %arg0, %c-1 : index
      %10 = addi %9, %c4 : index
      %11 = cmpi "slt", %c32, %10 : index
      %12 = select %11, %c32, %10 : index
      %13 = "gpu.thread_id"() {dimension = "x"} : () -> index
      %14 = "gpu.block_dim"() {dimension = "x"} : () -> index
      scf.for %arg1 = %13 to %12 step %14 {
        %15 = addi %arg0, %arg1 : index
        %16 = load %4[%15] : memref<4xf32>
        %17 = remf %16, %cst_0 : f32
        %18 = cmpf "one", %17, %cst : f32
        store %18, %1[%15] : memref<4xi1>
      }
    }
    scf.for %arg0 = %7 to %c4 step %8 {
      %9 = muli %arg0, %c-1 : index
      %10 = addi %9, %c4 : index
      %11 = cmpi "slt", %c32, %10 : index
      %12 = select %11, %c32, %10 : index
      %13 = "gpu.thread_id"() {dimension = "x"} : () -> index
      %14 = "gpu.block_dim"() {dimension = "x"} : () -> index
      scf.for %arg1 = %13 to %12 step %14 {
        %15 = addi %arg0, %arg1 : index
        %16 = load %4[%15] : memref<4xf32>
        %17 = remf %16, %cst_0 : f32
        %18 = cmpf "olt", %17, %cst : f32
        store %18, %2[%15] : memref<4xi1>
      }
    }
    scf.for %arg0 = %7 to %c4 step %8 {
      %9 = muli %arg0, %c-1 : index
      %10 = addi %9, %c4 : index
      %11 = cmpi "slt", %c32, %10 : index
      %12 = select %11, %c32, %10 : index
      %13 = "gpu.thread_id"() {dimension = "x"} : () -> index
      %14 = "gpu.block_dim"() {dimension = "x"} : () -> index
      scf.for %arg1 = %13 to %12 step %14 {
        %15 = addi %arg0, %arg1 : index
        %16 = load %4[%15] : memref<4xf32>
        %17 = remf %16, %cst_0 : f32
        %18 = addf %cst_0, %17 : f32
        store %18, %3[%15] : memref<4xf32>
      }
    }
    return
  }
  hal.interface @legacy_io attributes {sym_visibility = "private"} {
    hal.interface.binding @arg0, set=0, binding=0, type="StorageBuffer", access="Read"
    hal.interface.binding @ret0, set=0, binding=1, type="StorageBuffer", access="Write|Discard"
    hal.interface.binding @ret1, set=0, binding=2, type="StorageBuffer", access="Write|Discard"
    hal.interface.binding @ret2, set=0, binding=3, type="StorageBuffer", access="Write|Discard"
    hal.interface.binding @ret3, set=0, binding=4, type="StorageBuffer", access="Write|Discard"
  }
}
```

Stack trace:
```
0.	Program arguments: /usr/local/google/_blaze_laurenzo/e646f1420b8ad711ddb6ac93961b218a/execroot/google3/blaze-out/k8-dbg/bin/third_party/iree/iree/tools/iree-translate --iree-mlir-to-vm-bytecode-module --iree-vm-bytecode-module-output-format=mlir-text --iree-hal-target-backends=vulkan-spirv /usr/local/google/home/laurenzo/tmp/math.mlir -mlir-disable-threading -print-ir-before-all 
 #0 0x00005638f468c651 llvm::sys::PrintStackTrace(llvm::raw_ostream&) /proc/self/cwd/third_party/llvm/llvm-project/llvm/lib/Support/Unix/Signals.inc:569:11
 #1 0x00005638f468cae9 PrintStackTraceSignalHandler(void*) /proc/self/cwd/third_party/llvm/llvm-project/llvm/lib/Support/Unix/Signals.inc:625:1
 #2 0x00005638f468b06b llvm::sys::RunSignalHandlers() /proc/self/cwd/third_party/llvm/llvm-project/llvm/lib/Support/Signals.cpp:67:5
 #3 0x00005638f468d15b SignalHandler(int) /proc/self/cwd/third_party/llvm/llvm-project/llvm/lib/Support/Unix/Signals.inc:406:1
 #4 0x00007f30553e79a0 __restore_rt (/usr/grte/v4/lib64/libpthread.so.0+0xf9a0)
 #5 0x00005638f459ecf0 mlir::TypeStorage::getDialect() /proc/self/cwd/third_party/llvm/llvm-project/mlir/include/mlir/IR/TypeSupport.h:46:5
 #6 0x00005638f459e878 mlir::Type::getDialect() const /proc/self/cwd/third_party/llvm/llvm-project/mlir/lib/IR/Types.cpp:25:37
 #7 0x00005638f459e895 mlir::Type::getContext() const /proc/self/cwd/third_party/llvm/llvm-project/mlir/lib/IR/Types.cpp:27:61
 #8 0x00005638f44d2155 mlir::TypeAttr::get(mlir::Type) /proc/self/cwd/third_party/llvm/llvm-project/mlir/lib/IR/Attributes.cpp:431:66
 #9 0x00005638f36f5a36 mlir::spirv::GlobalVariableOp::build(mlir::OpBuilder&, mlir::OperationState&, mlir::Type, llvm::StringRef, unsigned int, unsigned int) /proc/self/cwd/third_party/llvm/llvm-project/mlir/lib/Dialect/SPIRV/SPIRVOps.cpp:1725:25
```

Will update with further info.

**Comment by stellaraccident** [comment] 2020-05-28 23:10
Huh - looks like something more sinister. The assertion failure made me think it was complaining about an i1 memref.

**Comment by benvanik** [comment] 2020-05-28 23:11
I feel like it should have already been expanded to i8 by then, right?

**Comment by stellaraccident** [comment] 2020-05-28 23:20
Seems like it. And I just sent a change that upgrades the assert to a compile error and confirmed this is due to an i1 memref.

**Comment by hanhanW** [comment] 2020-06-02 07:35
I saw this error before, both in ASR encoder model and while.mlir test. In the past, we would rewrite it to storing an i8 in AdjustIntegerWidthPass. We might want to do the same thing here, maybe just add it to the StandardToSPIRV pass.

**Comment by stellaraccident** [comment] 2020-06-02 17:10
Summarizing the discussion on discord about this:

- We should promote/cast i1 at the ABI boundary.
- This might just be appropriate casts at the OutlineDispatchRegions level, where other type conversions are being done.

**Comment by antiagainst** [comment] 2020-06-03 15:00
Assigning to Hanhan for now given he worked on bitwidth handling.

**Comment by hanhanW** [comment] 2020-06-05 23:18
fyi, I got a prototype on this: https://reviews.llvm.org/D81317

**Comment by antiagainst** [comment] 2020-06-08 19:07
Hey @hanhanW, have you looked into fixing it by following the suggestion summarized in the above (https://github.com/google/iree/issues/2050#issuecomment-637687425)? [`LegalizeInputTypes`](https://github.com/google/iree/blob/master/iree/compiler/Dialect/Flow/Transforms/LegalizeInputTypes.cpp) might be a suitable place to have such logic, but @benvanik might have more thoughts regarding pass organization. Or at least we can reuse some of the logic there and make them common to share between passes. I'm afraid only fixing the SPIR-V CodeGen is just solving half of the problem and in the future we will be handling this again. (As commentedd in https://github.com/google/iree/issues/2022#issuecomment-640617234, this kind of runtime-kernel ABI mismatch can be hard to track down.)

**Comment by hanhanW** [comment] 2020-06-08 21:09
Oh, I somehow forgot it or misread something... sorry about that. Let me take a look at it again.

**Comment by hanhanW** [comment] 2020-06-08 22:25
I feel that `LegalizeInputTypes` pass is not a place to have this logic because we don't want to convert all i1 types to i8 types. Some operations take i1 as input, e.g., xla_hlo.select, std.cond_br, etc.

Instead, I tried to create casting ops right before and after `iree.tensor.load` in PrePartitioningConversionPass when lowering extract_element op. However, it failed in a later pass.

Before the prototype:
```
 // *** IR Dump After mlir::iree_compiler::IREE::Flow::PrePartitioningConversionPass ***
 func @while() attributes {iree.module.export, iree.reflection = {f = "I1!R1!", fv = "1"}} {
   %cst = constant dense<1> : tensor<i32>
   %cst_0 = constant dense<3> : tensor<i32>
   %cst_1 = constant dense<4> : tensor<i32>
   %0 = iree.do_not_optimize(%cst) : tensor<i32>
   %1 = iree.do_not_optimize(%cst_0) : tensor<i32>
   br ^bb1(%0 : tensor<i32>)
 ^bb1(%2: tensor<i32>):  // 2 preds: ^bb0, ^bb2
   %3 = "xla_hlo.compare"(%2, %1) {comparison_direction = "LT"} : (tensor<i32>, tensor<i32>) -> tensor<i1>
   %4 = flow.tensor.load %3 : tensor<i1>
   cond_br %4, ^bb2(%2 : tensor<i32>), ^bb3(%2 : tensor<i32>)
 ^bb2(%5: tensor<i32>):  // pred: ^bb1
   %6 = xla_hlo.add %5, %5 : tensor<i32>
   br ^bb1(%6 : tensor<i32>)
 ^bb3(%7: tensor<i32>):  // pred: ^bb1
   check.expect_eq(%7, %cst_1) : tensor<i32>
   return
 }
```

After the prototype, (see %4 and %6 in the snippet):
```
// *** IR Dump After mlir::iree_compiler::IREE::Flow::PrePartitioningConversionPass ***
 func @while() attributes {iree.module.export, iree.reflection = {f = "I1!R1!", fv = "1"}} {
   %cst = constant dense<1> : tensor<i32>
   %cst_0 = constant dense<3> : tensor<i32>
   %cst_1 = constant dense<4> : tensor<i32>
   %0 = iree.do_not_optimize(%cst) : tensor<i32>
   %1 = iree.do_not_optimize(%cst_0) : tensor<i32>
   br ^bb1(%0 : tensor<i32>)
 ^bb1(%2: tensor<i32>):  // 2 preds: ^bb0, ^bb2
   %3 = "xla_hlo.compare"(%2, %1) {comparison_direction = "LT"} : (tensor<i32>, tensor<i32>) -> tensor<i1>
   %4 = "xla_hlo.convert"(%3) : (tensor<i1>) -> tensor<i8>
   %5 = flow.tensor.load %4 : tensor<i8>
   %6 = trunci %5 : i8 to i1
   cond_br %6, ^bb2(%2 : tensor<i32>), ^bb3(%2 : tensor<i32>)
 ^bb2(%7: tensor<i32>):  // pred: ^bb1
   %8 = xla_hlo.add %7, %7 : tensor<i32>
   br ^bb1(%8 : tensor<i32>)
 ^bb3(%9: tensor<i32>):  // pred: ^bb1
   check.expect_eq(%9, %cst_1) : tensor<i32>
   return
 }
```

With the prototype, IdentifyDispatchRegions2Pass and FoldCompatibleDispatchRegionsPass can gather the compare op and convert op into one single dispatch. Then i1 types are eliminated, so codegen side won't need to handle it.

The issue here is that I don't know how to make it work with VM stuff. The truncate op right before cond_br will cause an error in the later pass `IREE::VM::ConversionPass`:

```
'vm.cond_br' op operand #0 must be 32-bit signless integer, but got 'i1'
```

I guess we want to erase `trunci` op in later pass (after std.cond_br got removed), but I'm not sure if this is a proper fix and I need to find a place to do it. Before jumping into this, @benvanik  do you have any idea for the root cause? Am I on a right way?

**Comment by hanhanW** [comment] 2020-06-08 23:13
update: I got a workaround is to do the same thing as IndexCastOp for TruncateIOp:

https://github.com/google/iree/blob/971cd746bc03b26dec139a27f7975820e16334ba/iree/compiler/Dialect/VM/Conversion/StandardToVM/ConvertStandardToVM.cpp#L293-L302

With this we can pass the test on vulkan-spirv and llvm-ir. There is an issue in VMLA, I'll look into what's happening.

**Comment by hanhanW** [comment] 2020-06-09 00:38
The reason is that vmla doesn't support converting i8 to i8. Ideally, we can fold this case, but I got stuck when add `let hasFolder = 1;` to VMLAOps.td. I expected the form like `OpFoldResult ConvertOp::fold(ArrayRef<Attribute> operand`, but got something like `LogicalResult  ConvertOp::fold(ArrayRef<Attribute> operands, SmallVectorImpl<OpFoldResult> &results)`. Maybe I just need more time to study how folder works...

A quick workaround is adding i8 to i8 casting support in VMLA, and it's working. I'll try to do it in proper way.

**Comment by benvanik** [comment] 2020-06-09 00:43
what does i8 to i8 casting mean? they are bitwise identical

**Comment by benvanik** [comment] 2020-06-09 00:48
the IREE VM does not support i1 - i1 values are always widened just like in any machine language to a representable size, which in the VM is 32-bits. So i1 of 0 -> i32 of 0 and i1 of 1 -> i32 of 1.

If you end up with i1 in VM conversion it means there is a missing pattern for whatever is producing the i1, as nothing in the VM can create anything but i32 values.

**Comment by hanhanW** [comment] 2020-06-09 00:53
The typeConverter will widen i1 to i8, so the op like `vmla.convert %4, out %5 : tensor<i1> -> tensor<i8>` (which is lowered from `%3 = "xla_hlo.convert"(%2) : (tensor<i1>) -> tensor<i8>`) will be lowered to `vm.call @vmla.convert.i8.i8...`.

So I think the better way is to erase `vmla.convert ... : tensor<i1> -> tensor<i8>` somewhere (maybe at [ConvertHLOToVMLA.cpp](https://github.com/google/iree/blob/master/iree/compiler/Dialect/VMLA/Conversion/HLOToVMLA/ConvertHLOToVMLA.cpp)).

For example, I think we can remove the second line of the snippet from IR if the src type and dst type are identical:
```
    ...
    %5 = vmla.buffer.alloc byte_length = %c1_3 : !vmla.buffer
    vmla.convert %4, out %5 : tensor<i1> -> tensor<i8>
    %6 = vmla.interface.binding %arg0 {binding = 2 : i32, set = 0 : i32} : !vmla.buffer
    ...
```

**Comment by benvanik** [comment] 2020-06-09 01:00
oh, VMLA != VM - tensors (tensor<i8>, etc) are used by VMLA and the VM only deals with primitive values (i32). You seem to be mentioning both here but I think the root cause is VMLA, and then the VM errors you are getting are caused downstream.

VMLA does not support tensors of i1. tensor<i1> must be converted to tensor<i8> *before* going into VMLA conversion. It's impossible to allocate a buffer of element size i1. Same as with any programming language; bool[4] in C is 4*8 bytes, etc. Since it's impossible to represent i1's in buffers, there's no need for a conversion. If you are hitting a conversion it means a tensor<i1> is not being converted to a tensor<i8> early enough.

Nothing should be able to create a tensor<i1> in VMLA, For example, vmla.cmp.X outputs an i8 buffer where i8=0 for false and i8=1 for true.

**Comment by antiagainst** [comment] 2020-07-20 21:37
I think Hanhan handled this previously. Closing.

**Closed by antiagainst** 2020-07-20 21:37 UTC
Labels: spirv
