### ISSUE TITLE
`linalg.fill` + `tensor.extract_slice` doesn't fold.

### ISSUE THREAD

**Issue by benvanik** [google/iree#8060] opened 2022-01-10 23:41 UTC
(from https://github.com/google/iree/issues/8030#issuecomment-1006991705)

The following does not fold:
```mlir
  %cst_4 = arith.constant 1.000000e+00 : f32
  %9 = linalg.init_tensor [%0, %8] : tensor<?x?xf32>
  %10 = linalg.fill(%cst_4, %9) : f32, tensor<?x?xf32> -> tensor<?x?xf32> 
  %38 = tensor.extract_slice %10[%31, 0] [%37, %8] [1, 1] : tensor<?x?xf32> to tensor<?x?xf32>
```

This should fold into a fill of the extracted size:
```mlir
  %cst_4 = arith.constant 1.000000e+00 : f32
  %9 = linalg.init_tensor [%37, %8] : tensor<?x?xf32>
  %38 = linalg.fill(%cst_4, %9) : f32, tensor<?x?xf32> -> tensor<?x?xf32> 
```

Today this sequence causes additional dispatches and tensor materializations as the fill + extract_slice don't get put into the same dispatch region.

(this should happen regardless of whether the fill value is constant)

**Comment by MaheshRavishankar** [comment] 2022-06-06 21:09
This is duplicate of #6901. Closing this in favor of that one.

**Closed by MaheshRavishankar** 2022-06-06 21:09 UTC
Labels: compiler/dialects, codegen, performance ⚡
