### ISSUE TITLE
unlegalized TFLite op during tflite->mlir conversion

### ISSUE THREAD

**Issue by pingpiang2019** [google/iree#7309] opened 2021-10-12 02:27 UTC
In the "Tensorflow Lite Integration" example, following errors are observed during tflite->mlir conversion. What's the nature of the issue? Is there any workaround?

```
test.tflite:0:0: error: 'tfl.batch_matmul' op : unlegalized TFLite op still exists
test.tflite:0:0: note: see current operation: %95 = "tfl.batch_matmul"(%94, %69) {adj_x = false, adj_y = true} : (tensor<192x3x16xf32>, tensor<?x3x16xf32>) -> tensor<192x3x3xf32>
test.tflite:0:0: error: 'tfl.batch_matmul' op : unlegalized TFLite op still exists
test.tflite:0:0: note: see current operation: %66 = "tfl.batch_matmul"(%arg4, %65) {adj_x = false, adj_y = true} : (tensor<192x41x16xf32>, tensor<?x41x16xf32>) -> tensor<192x41x41xf32>
test.tflite:0:0: error: 'tfl.batch_matmul' op : unlegalized TFLite op still exists
test.tflite:0:0: note: see current operation: %5346 = "tfl.batch_matmul"(%5345, %64) {adj_x = false, adj_y = true} : (tensor<192x10x16xf32>, tensor<?x10x16xf32>) -> tensor<192x10x10xf32>
test.tflite:0:0: error: 'tfl.l2_normalization' op : unlegalized TFLite op still exists
test.tflite:0:0: note: see current operation: %1070 = "tfl.l2_normalization"(%1069) {fused_activation_function = "NONE"} : (tensor<192x1x64xf32>) -> tensor<192x1x64xf32>
test.tflite:0:0: error: 'tfl.l2_normalization' op : unlegalized TFLite op still exists
test.tflite:0:0: note: see current operation: %1066 = "tfl.l2_normalization"(%1065) {fused_activation_function = "NONE"} : (tensor<192x50x64xf32>) -> tensor<192x50x64xf32>
test.tflite:0:0: error: 'tfl.l2_normalization' op : unlegalized TFLite op still exists
test.tflite:0:0: note: see current operation: %3207 = "tfl.l2_normalization"(%3206) {fused_activation_function = "NONE"} : (tensor<192x50x64xf32>) -> tensor<192x50x64xf32>
test.tflite:0:0: error: 'tfl.l2_normalization' op : unlegalized TFLite op still exists
test.tflite:0:0: note: see current operation: %3211 = "tfl.l2_normalization"(%3210) {fused_activation_function = "NONE"} : (tensor<192x1x64xf32>) -> tensor<192x1x64xf32>
test.tflite:0:0: error: The following TFLite operations still remain:
        tfl.batch_matmul (count: 3)
        tfl.l2_normalization (count: 4)
```

**Comment by rsuderman** [comment] 2021-10-12 21:17
It does not look like there is a lowering for `batch_matmul` or `l2_normalization` in TOSA legalization of TFLite. If you can share the model it would help debug the issue as generating sample cases is often a significant portion of the work.

**Comment by rsuderman** [comment] 2021-10-12 21:19
> @pingpiang2019 could you clarify your exact steps here? I assume you are talking about [google.github.io/iree/ml-frameworks/tensorflow-lite](https://google.github.io/iree/ml-frameworks/tensorflow-lite/), but that doesn't specify any specific input. I'm guessing you chose an arbitrary tflite file and it didn't convert. That's not unsurprising at this stage of the project. We don't have full coverage of all TFLite ops. In particular, the error message here is saying that we don't have lowerings for `batch_matmul` or `l2_normalization`. I'm not sure where those are on our priority list. @rsuderman would likely have a better idea
> 
> @rsuderman could you list a specific model in that getting started guide so we start users off on a known-working model?

As for specific working models, I would suggest [iree-samples](www.github.com/google/iree-samples). It contains a fairly wide set of working models with information on known failing models. It would still be useful to see the tflite model that caused the above failure so we can extend the legalize_tfl work.

**Comment by GMNGeoffrey** [comment] 2021-10-13 16:15
> Unfortunately, it's a business model which can not be shared :-(

Ah no worries, that's a problem I'm very familiar with :-) Something you can do is trim down the issue to an IR snippet that reproduces it. In this case, it would be pretty simple because it's just pointing at a single op. MLIR's crash reproducer generation can also be useful here: https://mlir.llvm.org/docs/PassManagement/#crash-and-failure-reproduction, which can help narrow down the problem. In the case of a large model, especially a confidential one, you'd still need manual changes to trim down the input though.

**Comment by rsuderman** [comment] 2021-11-30 23:54
Everything should be landed for these lowerings. Closing for now - if there is missing support feel free to open.

**Closed** 2021-12-01 00:18 UTC
Labels: bug 🐞, help wanted
