### ISSUE TITLE
IREE_TRACING_MODE=2 doesn't work on linux

### ISSUE THREAD

**Issue by hanhanW** [google/iree#2114] opened 2020-06-04 21:42 UTC
I hit an error with IREE_TRACING_MODE=2 mode. It seems that there is a bug in allocation tracking. This is the issue for tracking it.

![image](https://user-images.githubusercontent.com/6949191/83813096-90424980-a671-11ea-8b1c-340b73d12d79.png)

**Comment by benvanik** [comment] 2021-02-16 18:56
I'm going to close this as no-repro for now - having allocating tracing on is super useful to avoid runaway memory allocations like in #4852 and I can't reproduce this myself.

**Closed by benvanik** 2021-02-16 18:56 UTC
Labels: awaiting-triage, bug 🐞, runtime
