### ISSUE TITLE
Checked in bert file is not compatible with iree-run-module

### ISSUE THREAD

**Issue by ScottTodd** [google/iree#3577] opened 2020-10-22 17:15 UTC
The [bert_encoder_unrolled_fake_weights.mlir](https://github.com/google/iree/blob/main/iree/test/e2e/models/bert_encoder_unrolled_fake_weights.mlir) file contains some `check` dialect ops:

```
    check.expect_almost_eq_const(%5390, dense<895.256> : tensor<1x384xf32>) : tensor<1x384xf32>
    check.expect_almost_eq_const(%5392, dense<895.256> : tensor<1x384xf32>) : tensor<1x384xf32>
```

so it isn't compatible with a `iree-translate` -> `iree-run-module` workflow:
```
λ .\iree\tools\iree-translate.exe -iree-mlir-to-vm-bytecode-module -iree-hal-target-backends=vmla ../iree/iree/test/e2e/models/bert_encoder_unrolled_fake_weights.mlir -o ../iree-tmp/bert_encoder_unrolled_fake_weights_vmla.module
λ .\iree\tools\iree-run-module.exe --driver=vmla --entry_function=serving_default --module_file=../iree-tmp/bert_encoder_unrolled_fake_weights_vmla.module
Creating driver and device for 'vmla'...
Creating driver and device for 'vmla'...
Check failed: ::iree::IsOk(Run()) D:\dev\projects\iree\iree\vm\context.c:466: NOT_FOUND; module 'check' required for import 'check.expect_almost_eq' not registered with the context; creating context
```
<sup>(aside: why two "Creating driver..." logs?)</sup>

a simple fix is to change that file from using `check` to being a LIT test, but we could also host model files somewhere outside of the repo (with real weights) and advertise those.

**Comment by hanhanW** [comment] 2020-10-22 18:38
It will also run into timeout, IIRC. Overall the time is the same, the difference is to put the compilation time to the test time. (if using iree-run-mlir). And I think this will also remove it from Android test.

**Comment by GMNGeoffrey** [comment] 2020-10-22 21:00
Yeah there are reasons for things not being lit tests :-P

**Comment by benvanik** [comment] 2020-10-22 21:01
the pass needed (as discussed in discord) is as simple as what scott added for the $sync/$async shims, so someone just needs to do it

**Comment by GMNGeoffrey** [comment] 2020-10-22 21:02
I'll add my discord comment so people don't have to go hunting:

We discussed reworking check to do more work in the compiler. Then we could write tests like
```mlir
function foo(%arg0 : i32) {inputs = [3 : i32], expected_outputs = [6 : i32] } {
  %0 = addi %arg0 %arg0 : i32
  return %0 : i3
}
```

and a compiler pass would turn that into 

```mlir
function foo(%arg0 : i32) {
  %0 = addi %arg0 %arg0 : i32
  return %0 : i3
}

function $check_foo() {
  %c3 = iree.unfoldable_constant 3 : i32
  %0 = call @foo(%c3, %c3) : (i32, i32) -> i32
  check.expect_eq_const(%0, 6 : i32) : i32
  return
}
```

(the pass would have to be optional, obviously)

**Comment by ScottTodd** [comment] 2020-10-22 23:17
We don't necessarily need to change this test, but I do want there to be *some* bert file accessible to people without needing to run Bazel/Python code that is compatible with `iree-run-module`. it could be https://github.com/google/iree/blob/main/iree/test/e2e/models/bert_encoder_unrolled_fake_weights.mlir, it could be a file in https://github.com/google/iree/tree/main/iree/samples/models (like with MNIST), or it could be a file in public cloud storage that we reference in documentation somewhere.

Reworking `check` in the suggested ways sounds generally useful, but we don't need to go that far for this [yet].

**Comment by GMNGeoffrey** [comment] 2020-10-22 23:21
I already made a cloud bucket and uploaded the artifacts: https://storage.googleapis.com/iree-model-artifacts/iree-mobile-bert-artifacts-6fe4616e0ab9958eb18f368960a31276f1362029.tar.gz

**Comment by GMNGeoffrey** [comment] 2020-10-22 23:21
That bucket is world-readable and members of iree-team can upload new artifacts

**Comment by ScottTodd** [comment] 2020-10-26 16:46
Nice, thanks @GMNGeoffrey ! Let's mention that somewhere in code/docs?

Are there other artifacts there as well? If there isn't an index or directory listing already should we make our own?
I naively tried https://storage.googleapis.com/iree-model-artifacts/ but that 404s :P

**Comment by benvanik** [comment] 2020-11-22 06:15
Closing as a dupe of #1538 - we should have a pass that strips the check test dialect if wanting to produce standalone modules.

**Closed by benvanik** 2020-11-22 06:15 UTC
Labels: bug
