### ISSUE TITLE
SGD Not working with BERT 

### ISSUE THREAD

**Issue by raikonenfnu** [google/iree#6234] opened 2021-06-16 18:47 UTC
Hey guys, I am trying to compile (w/ iree.compiler.tf.compile_module) BERT.
Inference/predict seems to work fine. But when trying to compile learn/training, I got this following error:

```bash 
/path/to/python3.8/site-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py:714:0: error: could not lower resource op to flow: tf.ResourceScatterAdd
```

To reproduce:
```bash 
pip install gin-config
git clone https://github.com/raikonenfnu/ModelCompiler 
export PYTHONPATH=${PYTHONPATH}:$PWD/ModelCompiler/third_party/tf_models
cd ModelCompiler/nlp_gen
python bert_gen.py
```

IREE SNAPSHOT VERSION - releases/tag/snapshot-20210505.259

Thanks in advance guys :)

**Comment by stellaraccident** [comment] 2021-06-16 19:29
fyi - also needed to `pip install gin-config`

**Comment by stellaraccident** [comment] 2021-06-16 20:46
Ok, so I discovered that `iree-tf-opt` and the pass pipeline registration needs a fair bit of work to make triage simple. But I worked through it the hard way. FTR (and kicked off an internal discussion):

```
export IREE_SAVE_TEMPS="/tmp/ireedumps/{main}/{id}"
python bert_gen.py
```

This will dump a lot of temp files, including a reproducer. The pass-pipeline has a bunch of syntactic issues that I've enqueued issues for. Skipping to the end, here is a fragment of a command line that I manually fixed to work (requires https://github.com/google/iree/pull/6235):

```
iree-tf-opt-snapshot -pass-pipeline='symbol-dce, func(tf-executor-graph-pruning{}), tf-guarantee-all-funcs-one-use, func(tf-executor-graph-pruning{}, tf-executor-island-coarsening, tf-materialize-passthrough-op, canonicalize{  max-iterations=10 region-simplify=true top-down=true}), tf-shape-inference{max-iterations=10}, symbol-dce, func(tf-optimize, cse, tf-device-index-selector, iree-tf-strip-asserts), inline, canonicalize{  max-iterations=10 region-simplify=true top-down=true}, func(tf-device-decompose-resource-ops), iree-tf-propagate-resource-casts, tf-shape-inference{max-iterations=10}, func(tf-functional-control-flow-to-cfg), inline, symbol-dce, canonicalize{  max-iterations=10 region-simplify=true top-down=true}, iree-tf-convert-to-tf-strings, func(iree-tf-convert-to-tf-tensorlist, iree-tf-convert-to-mhlo{allow-partial-conversion=false device-type=INVALID_DEVICE_TYPE legalize-chlo=false use-tf2xla-fallback=false}), canonicalize{  max-iterations=10 region-simplify=true top-down=true}, tf-saved-model-optimize-global-tensors, func(remove-shape-constraints), canonicalize{  max-iterations=10 region-simplify=true top-down=true}, iree-tf-strings-convert-to-strings, iree-tf-tensorlist-convert-to-tensorlist, iree-tf-saved-model-lower-global-tensors' -verify-each /tmp/ireedumps/bert_gen.py/0/tf-reproducer.mlir -print-ir-before-all -mlir-elide-elementsattrs-if-larger=100
```

(this should have been copy-paste from the reproducer, but that will get better)

Result at the point of failure: https://gist.github.com/stellaraccident/30ffddc028b0941ec6c2c3a7a8b71290

**Comment by stellaraccident** [comment] 2021-06-16 20:52
Just looking through it, it looks to me like the missing `tf.ResourceScatterAdd` is indeed the one missing op (just using my eyes):

```
"tf.ResourceScatterAdd"(%arg4, %91, %627) {_class = ["loc:@bert_classifier/bert_encoder_1/word_embeddings/Gather/resource"], device = "/job:localhost/replica:0/task:0/device:CPU:0"} : (tensor<!tf.resource<tensor<100x768xf32>>>, tensor<512xi32>, tensor<512x768xf32>) -> ()
```

Here is the pass where these are lowered: https://github.com/google/iree/blob/main/integrations/tensorflow/iree_tf_compiler/TF/LowerGlobalTensors.cpp

We will likely want to decompose this op into primitives and then let the compiler handle it.

**Comment by benvanik** [comment] 2021-06-16 20:54
Yeah that should be able to become a variable load + scatter update + variable store (with in-place behavior being an optimization we can add)

**Comment by benvanik** [comment] 2021-06-16 20:56
(looks like there are a lot of ResourceScatter* ops - they should likely all be decomposed into resource load + op + store)

**Comment by stellaraccident** [comment] 2021-06-16 20:57
Probably a new IREE specific Resource decompose pass (since TF itself likes to keep these things fused into the composite form).

**Comment by stellaraccident** [comment] 2021-06-16 21:04
@benvanik / @hanhanW  Do we have the necessary ops supported (i.e. for the "scatter" part)?

**Comment by hanhanW** [comment] 2021-06-16 21:08
We don't have fully support for scatter ops, only scatter update works on CPU backend. I'm going to rework on scatter op and we will have more general support.

**Comment by benvanik** [comment] 2021-06-16 21:10
^ what he said - I think the first step of decomposing (there are tf.scatter_add/scatter_nd_add/etc) will let us see which of those are needed - but I don't expect many of those to work right away :P

**Comment by stellaraccident** [comment] 2021-06-16 21:36
So it sounds like this pass could be added ~now to do the decomposition, and then intersecting work will improve it over time.

@raikonenfnu I've got a full plate with other things right now. If you had cycles, it would be a good contribution to add (no pressure).

**Comment by stellaraccident** [comment] 2021-06-16 21:45
Could also add it directly to TensorFlow: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/mlir/tensorflow/transforms/decompose_resource_ops.td

Looking at the ones that are in there already, it might not be super controversial. Something tells me, though, that there is a reason that the scatter variants are not in there.

**Comment by raikonenfnu** [comment] 2021-06-16 21:59
@stellaraccident I have some cycles, and can start working on the pass to decompose, and try push up WIP/draft patch would probably need your/ben/hanhanw's guidance :)

**Comment by raikonenfnu** [comment] 2021-06-16 22:02
@stellaraccident is there a preference to push it up on TF or IREE? :)

**Comment by stellaraccident** [comment] 2021-06-16 22:16
I just confirmed with the TF team. This is just a missing pattern in decompose_resource_ops.td on the TensorFlow side: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/mlir/tensorflow/transforms/decompose_resource_ops.td (probably around line 345)

Do you want to push that or have us do it?

**Comment by raikonenfnu** [comment] 2021-06-16 23:23
@stellaraccident I'd like to take a crack at it, for the experience :)

**Comment by stellaraccident** [comment] 2021-06-16 23:37
> @stellaraccident I'd like to take a crack at it, for the experience :)

Go for it - let us know how it goes or if you need help.

**Comment by raikonenfnu** [comment] 2021-06-17 00:03
@stellaraccident we just need to add the decomposition pattern as such right:
https://github.com/raikonenfnu/tensorflow/commit/1408c2ea6876c762ca799bf6770ec59079cc42fa

if looks good, I am going to push a PR :)

**Comment by hanhanW** [comment] 2021-08-11 00:35
Closing the isssue, since scatter is working.

**Closed by hanhanW** 2021-08-11 00:35 UTC
Labels: integrations/tensorflow, awaiting-triage
