### ISSUE TITLE
elf loader segfault on 32-bit android arm

### ISSUE THREAD

**Issue by GMNGeoffrey** [google/iree#5561] opened 2021-04-22 01:36 UTC
We have a Google internal android 32-bit arm build and are seeing failures in the new elf module loading test. The error message leaves much to be desired:

```
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from ELFModuleTest
[ RUN      ] ELFModuleTest.Check
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
Segmentation fault 
logcat read failure: No such file or directory
```

**To Reproduce**
Well first we need an OSS arm32 config, and ideally a bot (which @asaadaldien is working on). Then try running the `iree/hal/local/elf/elf_module_test` and see if you get a qemu segfault.

For now, I have disabled this test internally.

**Comment by GMNGeoffrey** [comment] 2021-05-26 21:44
@asaadaldien what happened to your qemu work?

**Comment by asaadaldien** [comment] 2021-05-26 22:49
> @asaadaldien what happened to your qemu work?

It didn't get prioritized enough to push it forward. Is it a blocker now ? Also I have been doing qemu/docker for aarch64 (arm64) mainly for benchmarking / running on an arm64 linux SoC.

**Comment by GMNGeoffrey** [comment] 2021-06-14 18:29
The new version of the elf test fails unhelpfully (segfault with no info) on android arm64 emulators as well

**Comment by hcindyl** [comment] 2021-06-24 23:59
Hopefully it can be resolved after https://github.com/google/iree/pull/6312 is merged. It fixes RISC-V 32-bit codegen datatype issue, and I think it should be the same root cause for the segfault here.

**Comment by benvanik** [comment] 2021-08-30 22:34
We have bots running this fine now so I think it's fixed.

**Closed by benvanik** 2021-08-30 22:34 UTC
Labels: bug 🐞, platform/android 🤖
