### ISSUE TITLE
iree build error with pthread_trylock

### ISSUE THREAD

**Issue by Joejiong** [google/iree#6955] opened 2021-09-03 09:17 UTC
**To Reproduce**
1. Go to 'https://scotttodd.github.io/iree/building-from-source/getting-started/'
2. follow the step
3. See error
```
FAILED: iree/samples/simple_embedding/simple_embedding_vmvx_sync 
: && /usr/bin/cc -O2 -g -DNDEBUG  -lm -lpthread iree/samples/simple_embedding/CMakeFiles/iree_samples_simple_embedding_simple_embedding_vmvx_sync.dir/device_vmvx_sync.c.o iree/samples/simple_embedding/CMakeFiles/iree_samples_simple_embedding_simple_embedding_vmvx_sync.dir/simple_embedding.c.o  -o iree/samples/simple_embedding/simple_embedding_vmvx_sync  iree/samples/simple_embedding/libiree_samples_simple_embedding_simple_embedding_test_bytecode_module_vmvx_c.a  iree/base/libiree_base_base.a  iree/hal/libiree_hal_hal.a  iree/hal/local/libiree_hal_local_local.a  iree/hal/local/loaders/libiree_hal_local_loaders_vmvx_module_loader.a  iree/hal/local/libiree_hal_local_sync_driver.a  iree/modules/hal/libiree_modules_hal_hal.a  iree/vm/libiree_vm_bytecode_module.a  build_tools/third_party/flatcc/libflatcc_runtime.a  -lm  -lpthread  iree/modules/vmvx/libiree_modules_vmvx_vmvx.a  iree/hal/local/libiree_hal_local_local.a  iree/base/internal/libiree_base_internal_arena.a  iree/base/internal/libiree_base_internal_atomic_slist.a  iree/hal/libiree_hal_hal.a  iree/base/internal/libiree_base_internal_synchronization.a  iree/vm/libiree_vm_impl.a  iree/base/libiree_base_base.a && :
/usr/bin/ld: iree/base/internal/libiree_base_internal_synchronization.a(synchronization.c.o): in function `iree_mutex_try_lock':
/Workspace/iree/iree/base/internal/synchronization.c:253: undefined reference to `pthread_mutex_trylock'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
```

## After I set clang
the error became like this:
```
CMake Error at CMakeLists.txt:249 (include):
  include could not find load file:

    iree_macros


CMake Error at CMakeLists.txt:250 (include):
  include could not find load file:

    iree_copts


CMake Error at CMakeLists.txt:251 (include):
  include could not find load file:

    sanitizers


CMake Error at CMakeLists.txt:252 (include):
  include could not find load file:

    iree_cc_binary


CMake Error at CMakeLists.txt:253 (include):
  include could not find load file:

    iree_cc_library


CMake Error at CMakeLists.txt:254 (include):
  include could not find load file:

    iree_cc_test


CMake Error at CMakeLists.txt:255 (include):
  include could not find load file:

    iree_tablegen_library


CMake Error at CMakeLists.txt:256 (include):
  include could not find load file:

    iree_tablegen_doc


CMake Error at CMakeLists.txt:257 (include):
  include could not find load file:

    iree_third_party_cmake_options


CMake Error at CMakeLists.txt:258 (include):
  include could not find load file:

    iree_c_embed_data


CMake Error at CMakeLists.txt:259 (include):
  include could not find load file:

    iree_bytecode_module


CMake Error at CMakeLists.txt:260 (include):
  include could not find load file:

    iree_c_module


CMake Error at CMakeLists.txt:261 (include):
  include could not find load file:

    iree_python


CMake Error at CMakeLists.txt:262 (include):
  include could not find load file:

    iree_lit_test


CMake Error at CMakeLists.txt:263 (include):
  include could not find load file:

    iree_add_all_subdirs


CMake Error at CMakeLists.txt:264 (include):
  include could not find load file:

    iree_check_test


CMake Error at CMakeLists.txt:265 (include):
  include could not find load file:

    iree_run_binary_test


CMake Error at CMakeLists.txt:266 (include):
  include could not find load file:

    iree_mlir_benchmark_suite


CMake Error at CMakeLists.txt:280 (iree_append_list_to_string):
  Unknown CMake command "iree_append_list_to_string".


-- Configuring incomplete, errors occurred!
See also "/Workspace/iree-build/CMakeFiles/CMakeOutput.log".
make: *** No targets specified and no makefile found.  Stop.
```

**Comment by ScottTodd** [comment] 2021-09-03 15:04
The steps at https://google.github.io/iree/building-from-source/getting-started/ are most up to date, https://scotttodd.github.io/iree/building-from-source/getting-started/ is just my personal page that I use to show potential updates to the site.

The include message is weird. This should be setting up the path so those includes are successful: https://github.com/google/iree/blob/5b4e3e4147a3c8bdc2c06cbfb1ed6f2a8028d8b5/CMakeLists.txt#L172-L175

Maybe check your CMake version and try a clean rebuild?

**Comment by GMNGeoffrey** [comment] 2021-09-03 17:19
The first error looks like you're not getting -lpthread, or it's not being inserted in the right place, but of course we can see -lpthread in your command line. I expect this is a gcc/clang difference. Some more discussion here: https://github.com/google/iree/issues/5702. As noted in https://groups.google.com/g/iree-discuss/c/1mj0SoDzPa8, we consider gcc support "best effort" at the moment (I'm about to make this clearer in the documentation) so unless gcc is something you're really set on I recommend using clang. The latter error is likely due to CMake caching issues and I'd suggest doing a clean rebuild (delete the build dir) with clang set, as Scott mentions.

**Comment by GMNGeoffrey** [comment] 2022-06-14 01:37
Duplicate of #5702

**Closed by GMNGeoffrey** 2022-06-14 01:37 UTC
Labels: bug 🐞, help wanted, infrastructure, infrastructure/cmake, support
