### ISSUE TITLE
IREE runtime has unaligned memory access

### ISSUE THREAD

**Issue by hcindyl** [google/iree#6566] opened 2021-07-28 01:41 UTC
Some simple RISC-V machine may not have unaligned memory access support, and if the memory access does not align with the platform wordclass it could create issues (Renode has it defined in https://github.com/renode/renode-infrastructure/blob/4addfd8af53bfc684817704668a0ed8b24ea9bf4/src/Emulator/Cores/RiscV/BaseRiscV.cs#L462) and the default is false.

Run `iree/samples/simple_embedding/simple_embedding_embedded_sync` on x86_64

```
iree-build-host/iree/samples/simple_embedding/simple_embedding_embedded_sync 
.../iree/iree/hal/local/sync_device.c:83 device at 0x7ffff4644cb0 with size 8
.../ree/iree/hal/local/sync_device.c:86 device->loaders[0] at 0x1465355 with size 8
.../iree/iree/hal/local/sync_device.c:88 identifier.data at 0x1465350 with size 5
```
In qemu-riscv32
```
${QEMU32_BIN} -cpu rv32    iree-build-riscv_rv32/iree/samples/simple_embedding/simple_embedding_embedded_sync 
.../iree/iree/hal/local/sync_device.c:83 device at 0x407ff730 with size 4
.../iree/iree/hal/local/sync_device.c:86 device->loaders[0] at 0x5e06d with size 4
.../iree/iree/hal/local/sync_device.c:88 identifier.data at 0x5e068 with size 5
```
This will cause problems in the call of
https://github.com/google/iree/blob/cec4c67/iree/hal/local/sync_device.c#L84-L86

Is there ways we can align the fields better?

**Comment by benvanik** [comment] 2021-07-28 02:03
Ah fun. I should really fix the math to route through some macros where we can fix this (clamp up on sizeof(struct) to pointer alignment) - may make the code more readable too. I'll start fiddling with that and see if I can come up with something good!

**Comment by benvanik** [comment] 2021-07-28 02:05
oh and yeah having the identifier.data inside of the struct is silly - I'll fix that now and do a scrub to see if any other struct is doing it.

**Comment by benvanik** [comment] 2021-07-28 03:18
#6567 should fix this and hopefully a few other potential places there could be issues - may still be ones hiding.

**Comment by hcindyl** [comment] 2021-07-28 04:50
Cherry picked the PR and tested locally. Unfortunately there are others hiding indeed. :( Will try to provide more information.

**Comment by benvanik** [comment] 2021-07-28 04:51
darn :(

**Comment by hcindyl** [comment] 2021-07-28 05:48
Renode is not very cooperative with GDB step in... :( To the best I can tell so far the unaligned access happens at the `iree_vm_context_run_function(stack, module, "__init")` at https://github.com/google/iree/blob/main/iree/vm/context.c#L389 for the bytecode module.

**Comment by hcindyl** [comment] 2021-07-28 08:49
Found the code location that has the unaligned access. 
https://github.com/google/iree/blob/a595a8f/iree/vm/bytecode_dispatch.c#L780

![snipit_temp_3007092](https://user-images.githubusercontent.com/19485875/127292104-96716d0f-1699-4516-a2b1-f1899c9742cc.png)

Although Renode crashes at 0x30012998, there is a misaligned load at 0x30012988

**Comment by benvanik** [comment] 2021-07-28 14:18
Oof, that's going to be hard to fix as the bytecode is densely packed. I've been meaning to redo the encoding and can try to make it better next time around, but for now I think the only solution will be to have a variant of these OP_* macros that do the unaligned loads:
https://github.com/google/iree/blob/f8d05b196c747d1d55062eb34b3a66c07592afa7/iree/vm/bytecode_dispatch_util.h#L156

We can add an IREE_MEMORY_ACCESS_ALIGNED / IREE_MEMORY_ACCESS_UNALIGNED to iree/base/target_platform.h add some helpers for loading/storing at various widths, and switch them between the decomposed/combined variants.

I'll get that implemented now, and then we can figure out what toolchain preprocessor macros we can use to key off which path we should go down.

**Comment by benvanik** [comment] 2021-07-28 14:21
I forget - is unaligned access an optional riscv feature or to start could we say all riscv paths requirement alignment?

**Comment by hcindyl** [comment] 2021-07-28 16:09
It's an optional feature, and the HW would spend extra cycles(and RTL implementation) to decode it. It would be nice to see if SW can support it with a flag.

Thanks for the PR, I will test it and report back to the issue!

**Comment by benvanik** [comment] 2021-07-28 16:44
(whoops - I didn't mean to close this until we confirmed it all works)

**Comment by hcindyl** [comment] 2021-07-28 18:26
And the whack-a-mole continues... :(
Now it hits misaligned access during the second call of this from the bytecode module 
https://github.com/google/iree/blob/a595a8f/iree/vm/bytecode_dispatch.c#L1395

The last ASM call is 0x30016330

![snipit_temp_3108895](https://user-images.githubusercontent.com/19485875/127375994-959ff3a9-0e9f-4c4b-9337-a31ed1631a17.png)

**Comment by benvanik** [comment] 2021-07-28 18:29
darn - I suspect it's the register lists
https://github.com/google/iree/pull/6573 is still good but I'll need something else to handle those.

**Comment by benvanik** [comment] 2021-07-28 18:49
Definitely the register lists/remapping lists. That will be tricky to fix. I'll take a look this evening and see if there isn't something that can be done until the bytecode is reworked.

**Comment by benvanik** [comment] 2021-07-28 19:16
Since it all needs to be reworked anyway I'm going to try inserting padding on any register list - will send a PR when I have something we can try.

**Comment by benvanik** [comment] 2021-07-28 22:17
Update from @hcindyl: it works!
![image](https://user-images.githubusercontent.com/75337/127403284-e71059d1-827a-4736-b1d9-0df5b4dcff39.png)

We may still find other issues as porting progresses and more code paths are lit up. Closing this for now; we can reopen with more cases as they happen.

**Closed by benvanik** 2021-07-28 22:17 UTC
Labels: bug 🐞, hal/cpu, question ❔, runtime

**Comment by ImanHosseini** [comment] 2021-08-02 03:36
The _fix_ (https://github.com/google/iree/commit/082aacd3925385fbcba105d99edebe214b868df0) breaks MSVC support [as in: IREE no longer builds on windows] because MSVC does not support "_Generic":  https://www.reddit.com/r/cpp/comments/hjn4uv/c20_features_and_fixes_in_vs_2019_161_through_166/fwsil0q/?context=3
