### ISSUE TITLE
MobileNetV1 is 2.5x slower on linalg-on-tensors path on CPU

### ISSUE THREAD

**Issue by asaadaldien** [google/iree#5231] opened 2021-03-25 21:40 UTC
Main issue to triage  performance issues:
 
To generate iree input :
```
$ python ../integrations/tensorflow/e2e/slim_vision_models/slim_vision_model_test.py \ 
--model=mobilenet_v1_100_224 \
--target_backends=tf,iree_llvmaot \
--artifacts_dir=/tmp/artifacts  \
--tf_hub_url=https://tfhub.dev/google/imagenet/
 ```

**Comment by antiagainst** [comment] 2021-03-30 13:26
I also see performance regression on MobileNet v2 on GPUs after making it work on the tensor path. It's not as dramatic like what you see here though, like 1.5x. We are creating more dispatch regions, with ones that even just contain a single reshape op or fill op that zeros one scalar. I've a chain of CLs that will handle these inefficiencies, including enabling fusing with consumer element-wise ops. I'd expect v1 to improve too along the way.

**Comment by MaheshRavishankar** [comment] 2021-03-30 15:59
FYI, I am looking into making reshapes not survive upto the dispatch region creation itself. It is either fused away or it is converted to `flow.tensor.reshape`. Having reshape in dispatch region causes other problems.

**Comment by MaheshRavishankar** [comment] 2021-03-30 20:32
Can you add this pattern as a pre-processing step before dispatch region creation?

**Comment by antiagainst** [comment] 2021-03-30 21:03
It was changed to a pass to pick for each backend in https://github.com/google/iree/pull/4796. There are more background and discussions there but basically it was due to that we don't have good matmul tiling schemes to accelerate all the cases seen in MobileNet so I switched to directly tile and vectorize the convolution for GPU. Now might be the time to revisit. I will coordinate with Ahmed to improve this. 

In the meantime, Ahmed you can also feel free to pull in the patterns for direct tiling and vectorizing convolution, even for 1x1 cases. Curious how they will perform on CPU cases too.

**Comment by MaheshRavishankar** [comment] 2021-03-30 21:24
Looks like after that pass this was totally dropped from the LLVM side.

@asaadaldien even if you tile and distribute a convolution you should be able to convert a 1x1 tiled convolution to a matmul right? Maybe that will help you get the performance back to some extent.

**Comment by asaadaldien** [comment] 2021-03-31 05:40
The plan is to add and enable tile-distribute and vectorizations for convolution, we can convert 1x1 conv as long as having a workgroup dispatch with `reshape -> matmul -> reshape` isn good e.g not going to produce extra copies. 
But IMO moving it as pre-processing step is better.

**Comment by MaheshRavishankar** [comment] 2021-03-31 05:46
> we can convert 1x1 conv as long as having a workgroup dispatch with `reshape -> matmul -> reshape` isn good e.g not going to produce extra copies.

You can try it out today, and check that it doesnt. Just use the `iree-codegen-linalg-bufferize` pass with that example by hand and see that it doesnt (it shouldnt). Moving this upstream is going to undo a lot of the optimization work that was done on MobileNet. So unless there is no go and we need to re-evaluate, I would go down the path of doing this after tile + distribute.

**Comment by asaadaldien** [comment] 2021-03-31 05:56
> > we can convert 1x1 conv as long as having a workgroup dispatch with `reshape -> matmul -> reshape` isn good e.g not going to produce extra copies.
> 
> You can try it out today, and check that it doesnt. Just use the `iree-codegen-linalg-bufferize` pass with that example by hand and see that it doesnt (it shouldnt). Moving this upstream is going to undo a lot of the optimization work that was done on MobileNet. So unless there is no go and we need to re-evaluate, I would go down the path of doing this after tile + distribute.

1x1 conv is a matmul, what is missing in the GPU pass is the ability to tile-and-distribute the odd shapes from the conversion which is needed anyway for matmul perf

**Comment by asaadaldien** [comment] 2021-03-31 06:21
Yeah not considering moving and applying pattern today :), and if moved soon it will be with optional with default off (temporarily since the fix will be to remove the flag). My understanding is @ThomasRaoux is re-visiting the tilling config for matmul soonish. In the mean time I am going to:

- Bring up tile-distribute-vectorization of conv to CPU
- Evaluate the 1x1 case vs matmul of the same problem size.

By the time I am done with these will be easy to reevaluate.

**Comment by MaheshRavishankar** [comment] 2021-05-21 19:58
I think this is fixed now. Closing

**Closed by MaheshRavishankar** 2021-05-21 19:58 UTC
Labels: codegen, codegen/llvm, performance ⚡
