### ISSUE TITLE
 No such package 'integrations/tensorflow/e2e'

### ISSUE THREAD

**Issue by chiachia36** [google/iree#7421] opened 2021-10-21 15:35 UTC
Hi,
I tried to run e2e test. ([TensorFlow e2e tests](https://github.com/google/iree/tree/main/integrations/tensorflow/e2e))

I met some problems, when I ran the command `bazel run //integrations/tensorflow/e2e:conv_test_manual` in the section **Running Tests**.

Here is my error message.
```
ERROR: Skipping '//integrations/tensorflow/e2e:conv_test_manual': no such package 'integrations/tensorflow/e2e': Package is considered deleted due to --deleted_packages
WARNING: Target pattern parsing failed.
ERROR: no such package 'integrations/tensorflow/e2e': Package is considered deleted due to --deleted_packages
INFO: Elapsed time: 0.252s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded)
```

Thanks!

**Comment by GMNGeoffrey** [comment] 2021-11-05 22:30
Duplicate of #7422

**Closed by GMNGeoffrey** 2021-11-05 22:31 UTC
Labels: bug 🐞, help wanted
