### ISSUE TITLE
Improve flexibility of CMake target

### ISSUE THREAD

**Issue by ThomasRaoux** [google/iree#5893] opened 2021-05-14 02:31 UTC
In CUDA build file we had to disable bazel_to_make because CMake doesn't support an equivalent of `filetarget`:

https://github.com/google/iree/blob/main/iree/compiler/Dialect/HAL/Target/CUDA/CMakeLists.txt

Improve the flexibility of CMake build system to be able to solve this problem.

**Comment by ScottTodd** [comment] 2022-03-08 01:12
This issue seems to be obsolete given changes in our CMake CUDA configuration. Can we close this issue?

**Comment by ThomasRaoux** [comment] 2022-03-08 01:48
> This issue seems to be obsolete given changes in our CMake CUDA configuration. Can we close this issue?

We can be I really hope we can go back to embedding the libdevice file at some point as it significantly improve usability of the compiler

**Comment by benvanik** [comment] 2022-03-08 01:52
big +1 - encountered this today - is there a blocker on adding it back?

**Comment by GMNGeoffrey** [comment] 2022-06-14 01:25
I'm going to close this as a duplicate of the more general and detailed #8761

**Comment by GMNGeoffrey** [comment] 2022-06-14 01:25
Duplicate of #8761

**Closed by GMNGeoffrey** 2022-06-14 01:25 UTC
Labels: bug 🐞, help wanted, infrastructure
