### ISSUE TITLE
GPU benchmarks do not reflect the real performance.

### ISSUE THREAD

**Issue by hanhanW** [google/iree#5248] opened 2021-03-30 14:48 UTC
We are using batch mode (which was introduced in #5012) to benchmark MobileBert and MobileNetV2. This can help us to amortize overhead. However, the numbers are much smaller in many cases, especially when increasing the batch size. We think that this is because of missing barriers. Instead of duplicating hal.command_buffer.dispatch ops, we should probably submit the command buffer multiple times. If this works, it will address the issue (see #5052) of enabling batch mode on Pixel 4.

The below snippet is from @antiagainst

>I think it's likely because we duplicate dispatches without inserting any barriers. That essentially means increasing the number of warps for each dispatch to help filling the GPU. After dividing by the repeat count, we are getting a better number than it should be. There are certain dispatches in both models that are just working on small scale problem size; increasing warp count hides and "improves" the latency for them. Instead of duplicating dispatches, I think we want to submit the command buffer multiple times and average at that level. It will help to keep the original dispatch structure intact.

**Comment by hanhanW** [comment] 2021-03-30 14:50
This also blocks adding mobile-bert f16 version to Mako benchmark, see #5204

One sample run with batch_size=16 for MobilBert f16.

```
-------------------------------------------------------------------------------------------
Benchmark                                                 Time             CPU   Iterations
-------------------------------------------------------------------------------------------
BM_serving_default/process_time/real_time               157 ms         37.7 ms           16
BM_serving_default/process_time/real_time              90.3 ms         29.8 ms           16
BM_serving_default/process_time/real_time              91.3 ms         31.5 ms           16
BM_serving_default/process_time/real_time              87.7 ms         27.8 ms           16
BM_serving_default/process_time/real_time              89.5 ms         27.6 ms           16
BM_serving_default/process_time/real_time              88.8 ms         28.5 ms           16
BM_serving_default/process_time/real_time              90.1 ms         29.6 ms           16
BM_serving_default/process_time/real_time              90.2 ms         29.8 ms           16
BM_serving_default/process_time/real_time              90.4 ms         29.9 ms           16
BM_serving_default/process_time/real_time               150 ms         30.9 ms           16
BM_serving_default/process_time/real_time              89.9 ms         29.6 ms           16
BM_serving_default/process_time/real_time              89.9 ms         29.6 ms           16
BM_serving_default/process_time/real_time              89.7 ms         29.9 ms           16
BM_serving_default/process_time/real_time               150 ms         31.5 ms           16
BM_serving_default/process_time/real_time              89.5 ms         29.5 ms           16
BM_serving_default/process_time/real_time              91.1 ms         30.9 ms           16
BM_serving_default/process_time/real_time               148 ms         29.0 ms           16
BM_serving_default/process_time/real_time              86.7 ms         26.6 ms           16
BM_serving_default/process_time/real_time              86.5 ms         26.2 ms           16
BM_serving_default/process_time/real_time              87.5 ms         27.2 ms           16
BM_serving_default/process_time/real_time_mean          102 ms         29.7 ms           20
BM_serving_default/process_time/real_time_median       90.0 ms         29.6 ms           20
BM_serving_default/process_time/real_time_stddev       25.6 ms         2.44 ms           20
```

**Comment by antiagainst** [comment] 2021-03-30 15:26
To submit the command buffer multiple times, I think we just need to drop the `OneShot` when creating the command buffer, and extend `hal.ex.submit_and_wait` to take multiple command buffers. Seems quite straightforward. @benvanik please correct me if I missed something. :D

**Comment by benvanik** [comment] 2021-03-30 15:29
I believe only one-shot command buffers are supported right now, though I've been meaning to support reusable ones. It requires some work on the CPU side to make work.

I'm doing some other cleanup on the HAL and can work on removing the submit_and_wait and replacing it with proper submission, in which case you'd be able to submit multiple command buffers (the same multiple times, or multiple ones that were recorded). I'll file an issue!

**Comment by benvanik** [comment] 2021-03-30 15:52
filed: https://github.com/google/iree/issues/5249 https://github.com/google/iree/issues/5250

**Comment by benvanik** [comment] 2021-03-31 02:09
update to the update: I think with some trickery tracy could work with reusable command buffers - it'd be a bigger implementation though and I won't be able to do it in the first go (of the same style of complexity as the timeline semaphore emulation).

**Comment by antiagainst** [comment] 2021-03-31 16:13
> (oh to clarify on those issues - I wanted to track them but I consider those/this issue lower priority than getting tracy support for vulkan working - I've always warned that this approach to measuring individual dispatches as being deceptive and brittle, and for pure interactive profiling the tracy approach will work better)

Point taken. IMO, there are two different use scenarios:

1. Having an overall number to show where we are regarding GPU performance on certain models. This is primarily for per-commit automated benchmarking and status tracking. There should be no manual work involved.
2. Looking at the details of all the dispatches in a model and figure out what's the performance bottleneck and why some regression reported by 1. There are manual work involved for sure because we need somebody staring at the charts/figures. :)

I see Tracy provides a great solution to 2. This issue is mostly for 1. Both are great to have. :)

**Comment by antiagainst** [comment] 2021-09-03 16:26
With #5919 and batching we have a temporary solution reflecting the kernel execution time for existing models. So closing this for now.

**Closed by antiagainst** 2021-09-03 16:26 UTC
Labels: compiler, performance ⚡
