### ISSUE TITLE
The examples in docs/get_started/ are outdated

### ISSUE THREAD

**Issue by hanhanW** [google/iree#4854] opened 2021-02-16 10:20 UTC
The `simple.mlir` file was split in 32b3101ba74d0283b49304d1e8062ba9a2db2585, there is no longer a `simple.mlir` file.

**Comment by ScottTodd** [comment] 2021-02-25 18:20
duplicate of https://github.com/google/iree/issues/4667

**Closed by ScottTodd** 2021-02-25 18:20 UTC
Labels: documentation ✏️
