### ISSUE TITLE
Hit illegal abi signature in PublicABIGenerationPass when there are non 32 bit types

### ISSUE THREAD

**Issue by hanhanW** [google/iree#5861] opened 2021-05-12 18:04 UTC
I hit the issue when compiling ASR models. I think we don't have well support for returning some types like ui64, i16, i64.

To repro:

```mlir
func @foo() -> (tensor<i64>, tensor<i32>, tensor<512xi16>, tensor<4x128xf32>, tensor<3x512xi16>, tensor<3xui64>) attributes {iree.module.export} {
  %0 = mhlo.constant dense<0> : tensor<i64>
  %1 = mhlo.constant dense<0> : tensor<i32>
  %2 = mhlo.constant dense<2> : tensor<3xi32>
  %3 = mhlo.constant dense<0> : tensor<512xi16>
  %4 = mhlo.constant dense<0.000000e+00> : tensor<4x128xf32>
  %5 = mhlo.constant dense<0> : tensor<3x512xi16>
  %6 = mhlo.constant dense<0> : tensor<3xui64>
  return %0, %1, %3, %4, %5, %6 : tensor<i64>, tensor<i32>, tensor<512xi16>, tensor<4x128xf32>, tensor<3x512xi16>, tensor<3xui64>
}
```

Run `iree-translate --iree-mlir-to-vm-bytecode-module --iree-hal-target-backends=dylib-llvm-aot ~/abi.mlir`

You will see the errors:

```
/usr/local/google/home/hanchung/abi.mlir:1:1: error: illegal abi signature ('I1!R43!B3!t7B3!t6B7!t5d512B7!d4d128B9!t5d3d512U1!'): Unrecognized raw tag
func @foo() -> (tensor<i64>, tensor<i32>, tensor<512xi16>, tensor<4x128xf32>, tensor<3x512xi16>, tensor<3xui64>) attributes {iree.module.export} {
```

**Comment by hanhanW** [comment] 2021-05-12 21:42
It looks like `ui64` is the root cause. I replace it with `i32`, then everything looks good.

**Comment by benvanik** [comment] 2021-06-08 15:39
Seems like a dupe of #6131. I think handling unsigned types is a meta-issue and should be fixed before we try to play whack-a-mole.

**Closed by benvanik** 2021-06-08 15:39 UTC
Labels: bug 🐞, compiler
