### ISSUE TITLE
Running the test for SelectOp on Spirv/Vulkan results in an "i1" type error

### ISSUE THREAD

**Issue by NatashaKnk** [google/iree#4833] opened 2021-02-12 00:06 UTC
SelectOp test for tosa->linalg lowering fails with the following error:

"error: 'spv.SConvert' op result #0 must be 8/16/32/64-bit integer or vector of 8/16/32/64-bit integer values of length 2/3/4/8/16 or Cooperative Matrix of 8/16/32/64-bit integer values, but got 'i1' "

**Comment by MaheshRavishankar** [comment] 2021-02-12 05:10
Could you post a repro please. Ideally it would be something that would be dump with the flags `-print-ir-after-all -mlir-disable-threading`

**Comment by antiagainst** [comment] 2021-02-16 22:20
+1. I suspect we might be missing a pattern when converting some value to a boolean.

**Comment by NatashaKnk** [comment] 2021-02-16 22:54
I'm not particularly sure what I should be looking for, so I would appreciate some help with that. The test fails with the above error when I run it normally, this is what I get running it with the flags you specified:

```
// *** IR Dump After TosaToLinalgOnTensors ***
func @tensor_float() attributes {iree.module.export} {
  %0 = iree.unfoldable_constant dense<[false, false, true, true]> : tensor<4xi1>
  %1 = iree.unfoldable_constant dense<[1.000000e+00, 5.000000e+00, 3.000000e+00, 4.000000e+00]> : tensor<4xf32>
  %2 = iree.unfoldable_constant dense<[5.000000e+00, 1.000000e+00, 3.000000e+00, 1.500000e+00]> : tensor<4xf32>
  %3 = linalg.init_tensor [4] : tensor<4xf32>
  %4 = linalg.generic {indexing_maps = [affine_map<(d0) -> (d0)>, affine_map<(d0) -> (d0)>, affine_map<(d0) -> (d0)>, affine_map<(d0) -> (d0)>], iterator_types = ["parallel"]} ins(%0, %1, %2 : tensor<4xi1>, tensor<4xf32>, tensor<4xf32>) outs(%3 : tensor<4xf32>) {
  ^bb0(%arg0: i1, %arg1: f32, %arg2: f32, %arg3: f32):  // no predecessors
    %5 = select %arg0, %arg1, %arg2 : f32
    linalg.yield %5 : f32
  } -> tensor<4xf32>
  check.expect_almost_eq_const(%4, dense<[5.000000e+00, 1.000000e+00, 3.000000e+00, 4.000000e+00]> : tensor<4xf32>) : tensor<4xf32>
  return
}
```

Is that helpful in any way?

The test itself is not in yet, the issue was created partially so I could link to it in the code in case this is an issue that takes a while to resolve.

**Comment by MaheshRavishankar** [comment] 2021-02-16 23:03
Thanks Natasha. That is helpful indeed, but I am sure there is more dump here. I would do this

```
$> <command> -print-ir-after-all -mlir-disable-threading 2> dump.after_all.mlir
```

Then you can just upload `dump.after_all.mlir` to gist.github.com and post the link here.

**Comment by MaheshRavishankar** [comment] 2021-02-16 23:04
If it is failing compilation, sometimes `-print-ir-before-all` is more informative than `-print-ir-after-all`

**Comment by NatashaKnk** [comment] 2021-02-16 23:16
Hm, this doesn't seem to change much (print-ir-before-all gives even less info than that). Maybe I'm running the command wrong? I've been using iree-opt but maybe I should be running it some other way?
[Here](https://gist.github.com/NatashaKnk/03058d4eb3e33faaaf2e704c14fd0a7c)'s the output file, which is basically just the output above duplicated (since the test runs both on ints and floats).

**Comment by MaheshRavishankar** [comment] 2021-02-17 00:48
I am not sure how `iree-opt` gave the error at the start of this bug report. The `iree-opt` command I see is just doing the single step of TOSA -> Linalg lowering. Then a whole gamut of passes are run to convert these to SPIR-V dialect. The error reported above is thrown in the SPIR-V dialect (cause SPIR-V doesnt support i1 types natively). You should either be running the pipeline passes (to convert from Flow -> HAL and executable translation pipeline in HAL to convert to SPIR-V) or you should be using `iree-translate` with at least these flags `-iree-mlir-to-vm-bytecode-module -iree-hal-target-backends=vulkan-spirv`. With this you can add `-print-ir-before-all -mlir-disable-threading` to see the IR after each pass of the translation.


@rsuderman might have something to add here that might be TOSA specific.

**Comment by hanhanW** [comment] 2021-02-17 07:04
Thanks for the snippet, I can help on this. It only shows up the IR after TosaToLinalgOnTensors because the passed pipeline is `--tosa-to-linalg-on-tensors`. We will get more information if we run `iree-translate` with the whole pipeline/translation. Basically, it will generate all the IRs until hitting an error.

I think I have some information to work on this, I will circle back with you once I get something.

**Comment by hanhanW** [comment] 2021-02-17 07:10
Ah, somehow the comments from Mahesh didn't show up when I replied. Yes, as Mahesh mentioned, the error happened in down stream, ie SPIR-V dialect. This is an issue in lowering standard ops to SPIR-V ops. I've added some support for i1 cases, but could miss some of them.

We already have some testing setup for TOSA ops, I will take a look in what other passes are needed. It will be great if you can also send out the link of your patch, so I can repro it easier on my local side.

**Comment by hanhanW** [comment] 2021-02-17 09:30
I can repro it easily on local side. The issue is the missing support for lowering trunci to SPIR-V. See the snippet:

```mlir
  func @tensor_float_ex_dispatch_0() {
    %c4 = constant 4 : index
    %0 = iree.placeholder for "interface buffer" {binding = @legacy_io::@ret0, operand_result_index = 3 : i32} : memref<4xf32>
    %1 = iree.placeholder for "interface buffer" {binding = @legacy_io::@arg0} : memref<4xi8>
    %2 = iree.placeholder for "interface buffer" {binding = @legacy_io::@arg1, operand_result_index = 1 : i32} : memref<4xf32>
    %3 = iree.placeholder for "interface buffer" {binding = @legacy_io::@arg2, operand_result_index = 2 : i32} : memref<4xf32>
    %4 = "gpu.block_id"() {dimension = "x"} : () -> index
    %5 = "gpu.block_dim"() {dimension = "x"} : () -> index
    %6 = "gpu.thread_id"() {dimension = "x"} : () -> index
    %7 = muli %4, %5 : index
    %8 = addi %7, %6 : index
    %9 = cmpi slt, %8, %c4 : index
    scf.if %9 {
      %10 = load %1[%8] : memref<4xi8>
      %11 = load %2[%8] : memref<4xf32>
      %12 = load %3[%8] : memref<4xf32>
      %13 = trunci %10 : i8 to i1
      %14 = select %13, %11, %12 : f32
      store %14, %0[%8] : memref<4xf32>
    }
    return
  }
```

I will send out the fix.

**Comment by hanhanW** [comment] 2021-02-17 10:18
I think it is working with https://reviews.llvm.org/D96851

I tested it with the modified snippet:

```
func @tensor_int() -> tensor<4xi32> attributes {iree.module.export} {
  %0 = iree.unfoldable_constant dense<[false, false, true, true]> : tensor<4xi1>
  %1 = iree.unfoldable_constant dense<[1, 5, 3, 4]> : tensor<4xi32>
  %2 = iree.unfoldable_constant dense<[5, 1, 3, 1]> : tensor<4xi32>
  %3 = linalg.init_tensor [4] : tensor<4xi32>
  %4 = linalg.generic {indexing_maps = [affine_map<(d0) -> (d0)>, affine_map<(d0) -> (d0)>, affine_map<(d0) -> (d0)>, affine_map<(d0) -> (d0)>], iterator_types = ["parallel"]} ins(%0, %1, %2 : tensor<4xi1>, tensor<4xi32>, tensor<4xi32>) outs(%3 : tensor<4xi32>) {
  ^bb0(%arg0: i1, %arg1: i32, %arg2: i32, %arg3: i32):  // no predecessors
    %5 = select %arg0, %arg1, %arg2 : i32
    linalg.yield %5 : i32
  } -> tensor<4xi32>
  return %4 : tensor<4xi32>
}
```

Run `iree-run-mlir -export-all -iree-hal-target-backends=vulkan-spirv tosa.mlir` and it does output `4xi32=5 1 3 4`.

**Comment by hanhanW** [comment] 2021-02-17 15:25
The patch was landed. Feel free to reopen this if it's still an issue.

**Closed by hanhanW** 2021-02-17 15:25 UTC
Labels: codegen/spirv, hal/vulkan

**Comment by MaheshRavishankar** [comment] 2021-02-17 17:08
Awesome Hanhan! Thanks for the great triage and fix!
