### ISSUE TITLE
mobile_bert_squad_tests ConvertHLOToLinalgOnBuffersPass Failed due to not fusing everything in FusionOfTensorOpsPass  

### ISSUE THREAD

**Issue by asaadaldien** [google/iree#3402] opened 2020-10-08 17:22 UTC
It failed to fuse broadcast_in_dim with its reshape consumer.
Repro:``bazel run //integrations/tensorflow/e2e:mobile_bert_squad_tests_failing_mobile_bert_squad_test__tf__iree_llvmjit``
Useful IR snippets:
```
// *** IR Dump After mlir::iree_compiler::(anonymous namespace)::DecomposeHLOClampPass ***
func @serving_default_ex_dispatch_14() {
  %c0 = constant 0 : index
  %0 = hal.interface.load.tensor @legacy_io::@arg0, offset = %c0 : tensor<384x128xf32>
  %1 = hal.interface.load.tensor @legacy_io::@arg1, offset = %c0 : tensor<128xf32>
  %2 = "mhlo.broadcast_in_dim"(%1) {broadcast_dimensions = dense<1> : tensor<1xi64>} : (tensor<128xf32>) -> tensor<384x128xf32>
  %3 = mhlo.add %0, %2 : tensor<384x128xf32>
  %4 = "mhlo.reshape"(%3) : (tensor<384x128xf32>) -> tensor<1x384x4x32xf32>
  %5 = "mhlo.transpose"(%4) {permutation = dense<[0, 2, 1, 3]> : tensor<4xi64>} : (tensor<1x384x4x32xf32>) -> tensor<1x4x384x32xf32>
  %6 = "mhlo.reshape"(%5) : (tensor<1x4x384x32xf32>) -> tensor<4x384x32xf32>
  hal.interface.store.tensor %6, @legacy_io::@ret0, offset = %c0 : tensor<4x384x32xf32>
  return
}

// *** IR Dump After mlir::iree_compiler::(anonymous namespace)::FusionOfTensorOpsPass ***
module {
  func @serving_default_ex_dispatch_14() {
    %c0 = constant 0 : index
    %0 = hal.interface.load.tensor @legacy_io::@arg1, offset = %c0 : tensor<128xf32>
    %1 = linalg.generic {indexing_maps = [affine_map<(d0, d1) -> (d1)>, affine_map<(d0, d1) -> (d0, d1)>], iterator_types = ["parallel", "parallel"]} ins(%0 : tensor<128xf32>) {
    ^bb0(%arg0: f32):  // no predecessors
      linalg.yield %arg0 : f32
    } -> tensor<384x128xf32>
    %2 = hal.interface.load.tensor @legacy_io::@arg0, offset = %c0 : tensor<384x4x32xf32>
    %3 = linalg.tensor_reshape %1 [affine_map<(d0, d1, d2) -> (d0)>, affine_map<(d0, d1, d2) -> (d1, d2)>] : tensor<384x128xf32> into tensor<384x4x32xf32>
    %4 = linalg.generic {indexing_maps = [affine_map<(d0, d1, d2) -> (d1, d0, d2)>, affine_map<(d0, d1, d2) -> (d1, d0, d2)>, affine_map<(d0, d1, d2) -> (d0, d1, d2)>], iterator_types = ["parallel", "parallel", "parallel"]} ins(%2, %3 : tensor<384x4x32x
    ^bb0(%arg0: f32, %arg1: f32):  // no predecessors
      %5 = addf %arg0, %arg1 : f32
      linalg.yield %5 : f32
    } -> tensor<4x384x32xf32>
    hal.interface.store.tensor %4, @legacy_io::@ret0, offset = %c0 : tensor<4x384x32xf32>
    return
  }
  hal.interface @legacy_io attributes {sym_visibility = "private"} {
    hal.interface.binding @arg0, set=0, binding=0, type="StorageBuffer", access="Read"
    hal.interface.binding @arg1, set=0, binding=1, type="StorageBuffer", access="Read"
    hal.interface.binding @ret0, set=0, binding=2, type="StorageBuffer", access="Write|Discard"
  }
}
```

**Comment by asaadaldien** [comment] 2020-10-08 17:54
IR before FusionOfTensorOpsPass
```
// *** IR Dump After Canonicalizer ***
module {
  func @serving_default_ex_dispatch_14() {
    %c0 = constant 0 : index
    %0 = hal.interface.load.tensor @legacy_io::@arg0, offset = %c0 : tensor<384x128xf32>
    %1 = hal.interface.load.tensor @legacy_io::@arg1, offset = %c0 : tensor<128xf32>
    %2 = linalg.generic {indexing_maps = [affine_map<(d0, d1) -> (d1)>, affine_map<(d0, d1) -> (d0, d1)>], iterator_types = ["parallel", "parallel"]} ins(%1 : tensor<128xf32>) {
    ^bb0(%arg0: f32):  // no predecessors
      linalg.yield %arg0 : f32
    } -> tensor<384x128xf32>
    %3 = linalg.generic {indexing_maps = [affine_map<(d0, d1) -> (d0, d1)>, affine_map<(d0, d1) -> (d0, d1)>, affine_map<(d0, d1) -> (d0, d1)>], iterator_types = ["parallel", "parallel"]} ins(%0, %2 : tensor<384x128xf32>, tensor<384x128xf32>) {
    ^bb0(%arg0: f32, %arg1: f32):  // no predecessors
      %6 = addf %arg0, %arg1 : f32
      linalg.yield %6 : f32
    } -> tensor<384x128xf32>
    %4 = linalg.tensor_reshape %3 [affine_map<(d0, d1, d2) -> (d0)>, affine_map<(d0, d1, d2) -> (d1, d2)>] : tensor<384x128xf32> into tensor<384x4x32xf32>
    %5 = linalg.generic {indexing_maps = [affine_map<(d0, d1, d2) -> (d1, d0, d2)>, affine_map<(d0, d1, d2) -> (d0, d1, d2)>], iterator_types = ["parallel", "parallel", "parallel"]} ins(%4 : tensor<384x4x32xf32>) {
    ^bb0(%arg0: f32):  // no predecessors
      linalg.yield %arg0 : f32
    } -> tensor<4x384x32xf32>
    hal.interface.store.tensor %5, @legacy_io::@ret0, offset = %c0 : tensor<4x384x32xf32>
    return
  }
  hal.interface @legacy_io attributes {sym_visibility = "private"} {
    hal.interface.binding @arg0, set=0, binding=0, type="StorageBuffer", access="Read"
    hal.interface.binding @arg1, set=0, binding=1, type="StorageBuffer", access="Read"
    hal.interface.binding @ret0, set=0, binding=2, type="StorageBuffer", access="Write|Discard"
  }
}
```

**Comment by MaheshRavishankar** [comment] 2020-10-08 17:56
After patch [D89002](https://reviews.llvm.org/D89002) and pulling it into IREE

```
module {
  func @serving_default_ex_dispatch_14() {
    %c0 = constant 0 : index
    %0 = hal.interface.load.tensor @legacy_io::@arg0, offset = %c0 : tensor<384x4x32xf32>
    %1 = hal.interface.load.tensor @legacy_io::@arg1, offset = %c0 : tensor<4x32xf32>
    %2 = linalg.generic {indexing_maps = [#map0, #map1, #map2], iterator_types = ["parallel", "parallel", "parallel"]} ins(%0, %1 : tensor<384x4x32xf32>, tensor<4x32xf32>) {
    ^bb0(%arg0: f32, %arg1: f32):  // no predecessors
      %3 = addf %arg0, %arg1 : f32
      linalg.yield %3 : f32
    } -> tensor<4x384x32xf32>
    hal.interface.store.tensor %2, @legacy_io::@ret0, offset = %c0 : tensor<4x384x32xf32>
    return
  }
  hal.interface @legacy_io attributes {sym_visibility = "private"} {
    hal.interface.binding @arg0, set=0, binding=0, type="StorageBuffer", access="Read"
    hal.interface.binding @arg1, set=0, binding=1, type="StorageBuffer", access="Read"
    hal.interface.binding @ret0, set=0, binding=2, type="StorageBuffer", access="Write|Discard"
  }
}
```

**Comment by asaadaldien** [comment] 2020-10-08 17:56
Awesome!

**Comment by MaheshRavishankar** [comment] 2020-10-15 22:03
This is duplicate of #3302

**Closed by MaheshRavishankar** 2020-10-15 22:03 UTC
Labels: codegen
