### ISSUE TITLE
Fusion of Tensor Ops produces invalid IR when encountering `linalg.index`

### ISSUE THREAD

**Issue by rsuderman** [google/iree#7316] opened 2021-10-12 21:15 UTC
**Describe the bug**
Tensor fusion can produce invalid IR when fusing a linalg.generic that includes a linalg.index. Specifically it appears to collapse to fewer dimensions that the requested linalg.index.

This likely means we are not remapping linalg.index values.

**To Reproduce**

1. Download corresponding [tosa.zip](https://github.com/google/iree/files/7333180/tosa.zip)
2. Unzip tosa.mlir file contained
3. Compile with tosa frontend flags

```
ireec tosa.mlir --iree-input-type=tosa --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=dylib-llvm-aot -o=/tmp/module.bytecode --iree-mlir-to-vm-bytecode-module --mlir-print-debuginfo --mlir-print-op-on-diagnostic=false --print-ir-before-all --mlir-elide-elementsattrs-if-larger=8 --mlir-disable-threading 2> /tmp/error.mlir
```

Failure is as follows:

```
tosa.mlir:269:12: error: 'linalg.index' op expected dim (2) to be lower than the number of loops (2) of the enclosing LinalgOp
%266 = "tosa.resize"(%265) {mode = "BILINEAR", offset = [0, 0], offset_fp = [-2.500000e-01 : f32, -2.500000e-01 : f32], output_size = [12, 12], shift = 0 : i32, stride = [0, 0], stride_fp = [5.000000e-01 : f32, 5.000000e-01 : f32]} : (tensor<1x6x6x64xf32>) -> tensor<1x12x12x64xf32>
```

Proposed Fix:
Include checks for contained `linalg.index` ops and verify that they do not attempt to collapse those dimension and remap appropriately.

**Comment by MaheshRavishankar** [comment] 2021-10-12 21:20
We should be remapping index values, but maybe that is not being done. Ill take a look, but it will be 2-3 days?

**Comment by MaheshRavishankar** [comment] 2021-10-12 21:51
whats more interesting is that we havent hit it so far. If you manage to get a smaller repro, then it would help speed things up/maybe we can pull Tobias in to fix it (cause it was probably caused by the deprecation of `linalg.indexed_generic`.

**Comment by MaheshRavishankar** [comment] 2022-01-21 17:51
THis should be fixed by https://reviews.llvm.org/D117856

**Closed** 2022-05-03 19:28 UTC
Labels: bug 🐞
