### ISSUE TITLE
spirv: error: 'spv.Store' op mismatch in result type and pointer type

### ISSUE THREAD

**Issue by silvasean** [google/iree#9156] opened 2022-05-18 14:04 UTC
**Describe the bug**

```
-:17:12: error: 'spv.Store' op mismatch in result type and pointer type
-:17:12: note: see current operation: "spv.Store"(%9, %0) : (!spv.ptr<i64, StorageBuffer>, i32) -> ()
```

Note: this is the same reproducer as https://github.com/google/iree/issues/9155 and https://github.com/google/iree/issues/9126 cc @hanhanW for insights.

Full error log: https://gist.github.com/silvasean/4136eaa19f12910fc452ec76622bd157

Note: this blocks running BERT on IREE's vulkan backend!

**To Reproduce**

```
iree-compile --iree-hal-target-backends=vulkan  core-input.mlir
```

```
#map0 = affine_map<(d0, d1, d2, d3) -> (d0, d1, d2, d3)>
#map1 = affine_map<(d0, d1, d2, d3) -> (d0, d1, d2, 0)>
module attributes {torch.debug_module_name = "OnlyLogitsHuggingFaceModel"} {
  func.func @forward(%arg0: tensor<1x12xi64>, %arg1: tensor<1x12x12x12xf32>) -> tensor<1x12x12x1xf32> {
    %c0_i64 = arith.constant 0 : i64
    %cst = arith.constant -3.40282347E+38 : f32
    %0 = linalg.init_tensor [1, 12, 12, 1] : tensor<1x12x12x1xi64>
    %1 = linalg.fill ins(%c0_i64 : i64) outs(%0 : tensor<1x12x12x1xi64>) -> tensor<1x12x12x1xi64>
    %2 = linalg.init_tensor [1, 12, 12, 1] : tensor<1x12x12x1xf32>
    %3 = linalg.fill ins(%cst : f32) outs(%2 : tensor<1x12x12x1xf32>) -> tensor<1x12x12x1xf32>
    %4:2 = linalg.generic {indexing_maps = [#map0, #map1, #map1], iterator_types = ["parallel", "parallel", "parallel", "reduction"]} ins(%arg1 : tensor<1x12x12x12xf32>) outs(%3, %1 : tensor<1x12x12x1xf32>, tensor<1x12x12x1xi64>) {
    ^bb0(%arg2: f32, %arg3: f32, %arg4: i64):
      %5 = linalg.index 3 : index
      %6 = arith.index_cast %5 : index to i64
      %7 = arith.cmpf ogt, %arg2, %arg3 : f32
      %8 = arith.select %7, %arg2, %arg3 : f32
      %9 = arith.select %7, %6, %arg4 : i64
      linalg.yield %8, %9 : f32, i64
    } -> (tensor<1x12x12x1xf32>, tensor<1x12x12x1xi64>)
    return %4#0 : tensor<1x12x12x1xf32>
  }
}
```

**Comment by MaheshRavishankar** [comment] 2022-05-18 14:34
Haven't looked into it in detail, but if this is the same issue as the dynamic size stack that this produces, the solution is same as what @ThomasRaoux did on the CUDA side.

**Comment by ThomasRaoux** [comment] 2022-05-18 16:06
@silvasean, the problem is that the default target (SwiftShader) is not marked as supporting i64 therefore the lowering to SPIRV fails. Do we have to generate i64 in this case and do we expect it to work on target that don't support native i64?

**Comment by ThomasRaoux** [comment] 2022-05-18 16:07
using `--iree-flow-demote-i64-to-i32` also fixes it

**Comment by MaheshRavishankar** [comment] 2022-05-18 16:23
Thanks! Sorry, I got this error linked on a different issue so thought the root cause was something else. Dont think SPIR-V is going to support i64 anytime soon.

**Comment by silvasean** [comment] 2022-05-19 08:37
Cool.

@benvanik - ping on Gandalfing i64's to avoid this kind of confusion!

**Comment by MaheshRavishankar** [comment] 2022-05-19 16:35
As long as the backends dont handle we will have to force demote this to i32. There is nothing IREE can do really until SPIR-V backend in core  can emulate the i64 math in i32.

**Comment by antiagainst** [comment] 2022-05-19 16:51
I'll look at implementing i64 emulation later, given it's becoming more and more annoying.

**Comment by MaheshRavishankar** [comment] 2022-05-19 17:19
Would be a good starter task for folks interested in starting with SPIR-V dialect.

**Comment by ThomasRaoux** [comment] 2022-05-19 17:22
side question: does emulation has to be done during convert to spirv? I feel like this makes conversion to spirv quite complex. This could be done as a an arith -> arith transformation?

**Comment by MaheshRavishankar** [comment] 2022-05-19 17:24
`arith -> arith` conversion would be fine too. Also more portable. Issue is that some of this is to be triggered based on spir-v target information.

**Comment by antiagainst** [comment] 2022-05-19 17:38
We can certainly implement it as arith to arith patterns. But the thing is that we can only decide whether to enable such emulation by looking at the SPIR-V target environment. That would mean exposing the SPIR-V target environment up to arith level and somehow control the pass pipeline with the SPIR-V target environment.

**Comment by benvanik** [comment] 2022-05-19 17:42
I think it may be simpler than that: if there was a pass to do this then we would just add it in our pipeline dynamically here where we have the target environment: https://github.com/google/iree/blob/54d078cf0b4e3900e257522d49cf0f0f06940883/compiler/src/iree/compiler/Codegen/SPIRV/Passes.cpp/#L275

**Comment by antiagainst** [comment] 2022-05-23 23:46
Yup, agreed!

**Comment by antiagainst** [comment] 2022-05-23 23:50
SPIR-V i64 emulation is tracked separately by https://github.com/google/iree/issues/8702. The invalid `spv.Store` op generated by this example actually is due to inadequate capability check. (The element type x storage class x compute / storage capability matrix is just a mess in SPIR-V..) I have https://reviews.llvm.org/D126256 to fix. After that, we should see conversion failure instead.

**Comment by antiagainst** [comment] 2022-05-25 15:10
https://reviews.llvm.org/D126256 is landed. Closing given no further work required for this issue. (SPIR-V i64 emulation is tracked separately by https://github.com/google/iree/issues/8702.)

**Closed by antiagainst** 2022-05-25 15:10 UTC
Labels: bug 🐞, help wanted, codegen/spirv
