### ISSUE TITLE
Can't convert vector_transfer ops to LLVMIR if operands rank > 2 resulting from subview

### ISSUE THREAD

**Issue by asaadaldien** [google/iree#3676] opened 2020-10-30 20:49 UTC
There is a problem in lowering `vector.transfer_{read|write}` consider the following two examples:
```
#map0 = affine_map<(d0, d1)[s0] -> (d0 * 8 + s0 + d1)>
func @test4x4(%arg0: memref<8x8xf32>) {
  %cst = constant 0.0 : f32
  %c0 = constant 0 : index
  %0 = subview %arg0[%c0, %c0] [4, 4] [1, 1] : memref<8x8xf32> to memref<4x4xf32, #map0>
  %1 = vector.transfer_read %0[%c0, %c0], %cst {masked = [false]} : memref<4x4xf32, #map0>, vector<4xf32>
  return
}

#map1 = affine_map<(d0, d1, d2)[s0] -> (d0 * 64 + s0 + d1 * 8 + d2)>
func @test1x4x4(%arg0: memref<1x8x8xf32>) {
  %cst = constant 0.0 : f32
  %c0 = constant 0 : index
  %0 = subview %arg0[%c0, %c0, %c0] [1, 4, 4] [1, 1, 1] : memref<1x8x8xf32> to memref<1x4x4xf32, #map1>
  %1 = vector.transfer_read %0[%c0, %c0, %c0], %cst {masked = [false]} : memref<1x4x4xf32, #map1>, vector<4xf32>
  return
}
```
The latter `test1x4x4` fails because `map1` access isnt' contiguous which isn't true it fails because it applies `map1` with shape  `[1x4x4]` but its a result of `subview op` so instead it should get the shape of the root parent `1x8x8x` by walking up the chain of `subview` ops and check if `map1` is valid.

**Comment by asaadaldien** [comment] 2020-10-30 21:17
Or instead fold subviews into `transfer_reads`

**Comment by MaheshRavishankar** [comment] 2020-11-02 05:34
cc @ThomasRaoux

**Comment by ThomasRaoux** [comment] 2020-11-02 07:20
I'm not an expert of the conversion to LLVM but I don't understand how in the first example the memref is contiguous since the stride is first stride is 8 for a memref of 4x4.

I wonder if the code below is correct. Should it be `e = strides.size() - 1` instead of `e = strides.size() - 2`? (@nicolasvasilache)

```
// Otherwise, we must determine contiguity form shapes. This can only ever
  // work in static cases because MemRefType is underspecified to represent
  // contiguous dynamic shapes in other ways than with just empty/identity
  // layout.
  auto sizes = memRefType.getShape();
  for (int index = 0, e = strides.size() - 2; index < e; ++index) {
    if (ShapedType::isDynamic(sizes[index + 1]) ||
        ShapedType::isDynamicStrideOrOffset(strides[index]) ||
        ShapedType::isDynamicStrideOrOffset(strides[index + 1]))
      return None;
    if (strides[index] != strides[index + 1] * sizes[index + 1])
      return None;
  }
```

I believe the lowering should be able to handle those kind of cases but the problem is that we don't really know the alignment of the address accessed. Here the access is aligned on 4 elements but if we had something like the code below we couldn't generate correct code doing vector access. I'm not sure how that can be handled without having alignment information.
```
`%1 = vector.transfer_read %0[%c0, %c1], %cst {masked = [false]} : memref<4x4xf32, #map0>, vector<4xf32>`
```

Note that for the SPIR-V we do combine the TransferRead with the subview. We do:
```
%0 = subview %arg0[%c0, %c2, %c3] [1, 4, 4] [1, 1, 1] : memref<1x8x8xf32> to memref<1x4x4xf32, #map1>
%1 = vector.transfer_read %0[%c0, %c0, %c0], %cst {masked = [false]} : memref<1x4x4xf32, #map1>, vector<4xf32>
```
->
```
%1 = vector.transfer_read %0[%c0, %c2, %c3], %cst {masked = [false]} : memref<1x8x8xf32>, vector<4xf32>
```

**Comment by asaadaldien** [comment] 2020-11-02 17:19
Thanks @ThomasRaoux  for looking into this
The problem with `convertToLLVM` code snippit is `sizes` isn't the original map sizes (8x8) + what you mentioned its actually skipping the check for rank 2 this need to be fixed upstream.

As you mentioned we can do the same folding all subviews + vector.transfer ops e.g:
```
%0 = subview %arg0[%arg1, %arg2, %arg3] [1, 16, 16] [1, 1, 1] : memref<1x32x32xf32> to memref<1x16x16xf32, #map0>
%1 = subview %0[%arg4, %arg5, %arg6] [1, 8, 8] [1, 1, 1] : memref<1x16x16xf32> to memref<1x8x8xf32, #map0>
%3 = vector.transfer_read %1[%arg7, %arg8, %arg9], %cst {masked = [false]} : memref<1x8x8xm #map0>, vector<4xf32>
```
->
```
%0 = addi %arg1, %arg4 : index
%1 = addi %0, %arg7 : index
// add other offsets ...
vector.transfer_read %0, %arg0[%1, // other offsets..
```
Is this canonicalization pattern already in MLIR or IREE ?

**Comment by ThomasRaoux** [comment] 2020-11-02 17:40
> Is this canonicalization pattern already in MLIR or IREE ?
Currently this transformation is in `mlir/lib/Conversion/StandardToSPIRV/LegalizeStandardForSPIRV.cpp`. It has been added to solve a slightly different problem since for SPIR-V we don't have a true representation of memref so we need to be able to track the original memref coming from an argument or `alloc`. But if you think this is useful to you we can probably make it more generic?

**Comment by asaadaldien** [comment] 2020-11-03 06:35
Thanks @ThomasRaoux This is doing exactly what we want. The only thing I need to add is hosting the loop invraint indexing code and I can see the same performance. I am adding this pattern to my vectorization pass for now will send a diff to move it to vector/std transforms patterns.

**Closed** 2020-11-04 04:26 UTC
Labels: codegen
