### ISSUE TITLE
BERT inference with static input values is failing out on translation via iree-translate.

### ISSUE THREAD

**Issue by gprateek93** [google/iree#8752] opened 2022-04-04 14:29 UTC
The bert_inference IR with static inputs is failing when run via iree-translate.

Input IR: https://gist.github.com/gprateek93/ac3e0c91d8d9fe2358bf08d0e31d2e41

Command to reproduce: 
`iree-translate  bert_input.mlir --iree-hal-target-backends="dylib" --iree-mlir-to-vm-bytecode-module -mlir-disable-threading --print-ir-after-all -mlir-elide-elementsattrs-if-larger=16 -o bert.vmfb`

The IR is failing silently with no error message in the ``iree-utils-apply-patterns`` pass.

CC: @MaheshRavishankar @benvanik

**Comment by benvanik** [comment] 2022-04-04 15:28
I think the issue is this upstream pattern by @nirvedhmeshram:
[FoldFillWithGenericOp](https://github.com/llvm/llvm-project/blob/3ad6f535024c5b2c20f64aeea251fe96dbc88d4f/mlir/lib/Dialect/Linalg/IR/LinalgOps.cpp#L917-L938)

It replaces the uses of the linalg.generic argument with the fill value but does not remove the input leading it to trigger infinitely. This eventually causes the pattern application to bail: `The pattern rewrite doesn't converge after scanning 10 times`.

There's a missing pattern that would make this work which removes unused inputs from linalg ops - that'd help quite a bit as today even once this pattern kicks in those fills are still generated even though they're never used. In isolation though the pattern should be checking to see if the argument has any uses. This fixes it and stops the pattern application from bailing:
```c++
    for (OpOperand *opOperand : genericOp.getInputOperands()) {
      FillOp fillOp = opOperand->get().getDefiningOp<FillOp>();
      if (fillOp) {
        auto arg = payload.getArgument(opOperand->getOperandNumber());
        if (arg.use_empty())
          continue;  // bail if no uses
        fillFound = true;
        arg.replaceAllUsesWith(fillOp.value());
      }
    }
```

@nirvedhmeshram could you take a look at adding the upstream pattern to remove unused inputs? And/or making this pattern safe in isolation?

**Comment by benvanik** [comment] 2022-04-04 15:29
(I'll improve the error message on the pass - unfortunately the pattern application only prints errors in debug hence why it looked like there was no errors)

**Comment by nirvedhmeshram** [comment] 2022-04-04 15:34
@benvanik , we added a companion pattern for this behavior here
https://github.com/llvm/llvm-project/blob/main/mlir/lib/Dialect/Linalg/IR/LinalgOps.cpp#L859
If its still not dropping the input argument, that means it has a unique dimension in it that no other argument has.
Also, perhaps this change that will get upstreamed soon will fix this issue, becuase this pattern should have been a transform and not canonicaization in the first place.
https://reviews.llvm.org/D122847

**Comment by benvanik** [comment] 2022-04-04 15:37
I'll get the op it triggers on 1 sec - if it is needed for metadata then maybe it should be turning the input producer into an init_tensor - then the shape information is still available but the buffer contents (which are unused) will never be materialized.

**Comment by MaheshRavishankar** [comment] 2022-04-04 16:05
Way to fix this would be to check if the argument defined by the fill is used in the op. If not then the pattern shouldn't trigger

**Comment by nirvedhmeshram** [comment] 2022-04-05 20:15
@gprateek93 the fix has landed upstream. Please let me know if it fixes the issue
https://github.com/llvm/llvm-project/commit/01055ed1d72dd74d0dcdf29d2cb734704ad673cb

**Comment by gprateek93** [comment] 2022-04-06 09:20
I am not getting the previous error now, but I am getting a new error in the ``DemoteF64ToF32Pass``. 
Error: https://gist.github.com/gprateek93/746c4bc3fc11b63cbd3cdf7e059bf00b

CC: @benvanik

**Comment by benvanik** [comment] 2022-04-06 15:03
See #8745.

**Comment by pashu123** [comment] 2022-04-12 18:02
@gprateek93 Could you confirm it's showing this error  ```
Diagnostics:
<stdin>:638:12: error: 'memref.cast' op operand type 'memref<1x7x64xf32>' and result type 'memref<1x7x64xf32, affine_map<(d0, d1, d2)[s0] -> (d0 * 10752 + s0 + d1 * 1536 + d2)>>' are cast incompatible
    %172 = linalg.generic {indexing_maps = [#map8, #map7], iterator_types = ["parallel", "parallel", "parallel"]} ins(%171 : tensor<1x7x1536xf32>) outs(%167 : tensor<1x7x1536xf32>) {
           ^
<stdin>:23:3: note: called from
  func @forward(%arg0: tensor<1x7xi64>) -> tensor<1x2xf32> {
  ^
<stdin>:638:12: error: failed to run translation of source executable to target executable for backend #hal.executable.target<"llvm", "embedded-elf-x86_64", {cpu_features = "", data_layout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128", native_vector_size = 16 : index, target_triple = "x86_64-unknown-unknown-eabi-elf"}>
    %172 = linalg.generic {indexing_maps = [#map8, #map7], iterator_types = ["parallel", "parallel", "parallel"]} ins(%171 : tensor<1x7x1536xf32>) outs(%167 : tensor<1x7x1536xf32>) {
           ^
<stdin>:23:3: note: called from
  func @forward(%arg0: tensor<1x7xi64>) -> tensor<1x2xf32> {
  ^
<stdin>:638:12: error: failed to serialize executables
    %172 = linalg.generic {indexing_maps = [#map8, #map7], iterator_types = ["parallel", "parallel", "parallel"]} ins(%171 : tensor<1x7x1536xf32>) outs(%167 : tensor<1x7x1536xf32>) {
           ^
<stdin>:23:3: note: called from
  func @forward(%arg0: tensor<1x7xi64>) -> tensor<1x2xf32> {
  ^
compilation from source to vm failed


```

**Comment by gprateek93** [comment] 2022-04-13 05:32
> @gprateek93 Could you confirm it's showing this error ``` Diagnostics: :638:12: error: 'memref.cast' op operand type 'memref<1x7x64xf32>' and result type 'memref<1x7x64xf32, affine_map<(d0, d1, d2)[s0] -> (d0 * 10752 + s0 + d1 * 1536 + d2)>>' are cast incompatible %172 = linalg.generic {indexing_maps = [#map8, #map7], iterator_types = ["parallel", "parallel", "parallel"]} ins(%171 : tensor<1x7x1536xf32>) outs(%167 : tensor<1x7x1536xf32>) { ^ :23:3: note: called from func @forward(%arg0: tensor<1x7xi64>) -> tensor<1x2xf32> { ^ :638:12: error: failed to run translation of source executable to target executable for backend #hal.executable.target<"llvm", "embedded-elf-x86_64", {cpu_features = "", data_layout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128", native_vector_size = 16 : index, target_triple = "x86_64-unknown-unknown-eabi-elf"}> %172 = linalg.generic {indexing_maps = [#map8, #map7], iterator_types = ["parallel", "parallel", "parallel"]} ins(%171 : tensor<1x7x1536xf32>) outs(%167 : tensor<1x7x1536xf32>) { ^ :23:3: note: called from func @forward(%arg0: tensor<1x7xi64>) -> tensor<1x2xf32> { ^ :638:12: error: failed to serialize executables %172 = linalg.generic {indexing_maps = [#map8, #map7], iterator_types = ["parallel", "parallel", "parallel"]} ins(%171 : tensor<1x7x1536xf32>) outs(%167 : tensor<1x7x1536xf32>) { ^ :23:3: note: called from func @forward(%arg0: tensor<1x7xi64>) -> tensor<1x2xf32> { ^ compilation from source to vm failed

Yes, this is the error I am getting.

**Comment by MaheshRavishankar** [comment] 2022-05-03 19:28
I dont know if this is still an issue. AFAIK it isnt .I am closing this. Please reopen/file new bug if there is an issue

**Closed by MaheshRavishankar** 2022-05-03 19:28 UTC
Labels: bug 🐞, compiler
