### ISSUE TITLE
Fix 'reduce_window.mlir' on Vulkan

### ISSUE THREAD

**Issue by dcaballe** [google/iree#9161] opened 2022-05-18 22:21 UTC
`iree/test/e2e/xla_ops/check_vulkan-spirv_vulkan_reduce_window.mlir` fails after https://github.com/google/iree/pull/9140 integration with:
```
iree/runtime/src/iree/modules/check/module.cc:352: Failure
Failed
Expected near equality of these values. Contents does not match.
  lhs:
    2x2x2xf32=[[0 0][1 1]][[0 0][2 2]]
  rhs:
    2x2x2xf32=[[1 1][1 1]][[2 2][2 2]]
[  FAILED  ] module.cumsum_f32, where GetParam() = 5 (6 ms)
[----------] 6 tests from module (40 ms total)

[----------] Global test environment tear-down
[==========] 6 tests from 1 test suite ran. (40 ms total)
[  PASSED  ] 5 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] module.cumsum_f32, where GetParam() = 5

 1 FAILED TEST
```

The test has been disabled for now.

**Comment by hanhanW** [comment] 2022-05-19 04:17
It's passing on CI bots, and I can't reproduce it locally. Closing the issue.

**Closed by hanhanW** 2022-05-19 04:17 UTC
Labels: bug 🐞, help wanted
