### ISSUE TITLE
IR hitting  `TODO: synthesize dynamic dimensions/hoist logic` in `ConvertFlowToStream` pass.

### ISSUE THREAD

**Issue by pashu123** [google/iree#8055] opened 2022-01-09 15:10 UTC
The `bert-dynamic.mlir` obtained from torch-mlir is attached.

It is hitting this case which is marked as a TODO https://github.com/google/iree/blob/8a5816ef35af389e88b03ff4abd79d489718ff35/iree/compiler/Dialect/Stream/Conversion/FlowToStream/ConvertFlowToStream.cpp#L307

It can be reproduced by running: `iree-translate  bert-dynamic.mlir --iree-hal-target-backends=dylib --iree-mlir-to-vm-bytecode-module -o bert.vmfb`

I have uploaded the mlir file here: https://easyupload.io/83ub67

**Comment by benvanik** [comment] 2022-01-09 16:24
Duplicate of #8030.
(this is triggered because torch-mlir is treating shape dimensions as tensors - if it was using primitive values instead this path would not be hit)

**Closed by benvanik** 2022-01-09 16:24 UTC
Labels: compiler
