### ISSUE TITLE
Add 64bit emulation support for SPIR-V

### ISSUE THREAD

**Issue by powderluv** [google/iree#9332] opened 2022-06-04 06:24 UTC
Filing it as a continuation of the discussion here: https://discord.com/channels/689900678990135345/982385246475522098/982522383162290216

powderluv — Today at 10:53 PM
@Lei Zhang @Ben Vanik @Stella Laurenzo if you guys have any suggestions on this issue (https://github.com/google/iree/issues/9245) for the fix above (https://github.com/google/iree/pull/9307) or how we should go about this issue it would be very useful. Without this fix we can't run Vulkan+MiniLM-torch on M1 or Linux.
Ben Vanik — Today at 11:04 PM
hmm that's a brittle pattern - though the whole pass is brittle, so maybe that's ok - I don't have high hopes that the pass will survive for very long
I'd rather have the 64-bit emulation in vulkan and make people take the performance hit for authoring models that use 64-bit numbers - so bandaids like this may be fine if deleting it is the goal
I think narrowing constants with saturation may be better (that value of INT64_MAX should then become INT32_MAX)
yeah I think trying truncSSat for signless integers here and below: https://github.com/google/iree/blob/main/compiler/src/iree/compiler/Dialect/Util/Transforms/ConvertPrimitiveType.cpp#L79-L85 may work
it's still somewhat of a hack but is less brittle - won't have to play whack a mole with ops and special cases

**Comment by benvanik** [comment] 2022-06-04 13:05
Duplicate of #8702

**Closed by benvanik** 2022-06-04 13:05 UTC
Labels: bug 🐞
